### ISSUE TITLE
Upgrade from DB 2.27 to latest fails

### ISSUE THREAD

**Issue by pertoft** [msimerson/NicTool#100]
mysql> SELECT option_value FROM nt_options WHERE option_name="db_version";
+--------------+
| option_value |
+--------------+
| 2.27         |
+--------------+
1 row in set (0.00 sec)

Latest version from GIT

root@amnesio:/usr/local/nictool/server/sql# ./upgrade.pl
reading DB settings from ../lib/nictoolserver.conf
Please enter database host [127.0.0.1]:

Beginning SQL upgrades.
If any of the information is incorrect, press Control-C now!
-------------------------
DB_DSN:  DBI:mysql:database=nictool;host=localhost;port=3306
DB_USER: nictool
DB_PASS: nictool
-------------------------

You made a backup already, right?
  # mysqldump -u root -p nictool > nictool-2011-11-16.sql
  # gzip nictool-2011-11-16.sql

Hit return to continue...

Skipping v2.00 SQL updates (already applied).
Skipping v2.05 SQL updates (already applied).
Skipping v2.08 SQL updates (already applied).
Skipping v2.09 SQL updates (already applied).
Skipping v2.10 SQL updates (already applied).
Skipping v2.11 SQL updates (already applied).
Skipping v2.14 SQL updates (already applied).
Skipping v2.15 SQL updates (already applied).
Skipping v2.16 SQL updates (already applied).
Skipping v2.18 SQL updates (already applied).
Skipping v2.24 SQL updates (already applied).
Skipping v2.27 SQL updates (already applied).
applying v 2.28 SQL updates
ALTER TABLE nt_zone ADD COLUMN last_publish TIMESTAMP DEFAULT 0 AFTER last_modified;
DBI error: Duplicate column name 'last_publish' at ./upgrade.pl line 62, <STDIN> line 2.
root@amnesio:/usr/local/nictool/server/sql#

**Comment by pertoft** [comment]
I have manually changed the db version to 2.29:
UPDATE nt_options SET option_value='2.29' WHERE option_name='db_version';

This resolves the issue

**Comment by msimerson** [comment]
Right, so the 2.28 update was partially applied (apparently *before* the sequence of events shown. In such a case, the reviewer needs to scroll back, see what happened, and then either fix it themselves or report the problem that led to this.
