### ISSUE TITLE
nt_import.pl does not import reverse zones correct

### ISSUE THREAD

**Issue by pertoft** [msimerson/NicTool#101]
Reverse zone records starting with "0" are not imported. E.g. 0.138.80.85.in-addr.arpa is not imported.

Example reverse zone file:

$TTL 3600
@               IN      SOA     ns1.cybercity.dk.       zonec.cybercity.dk. (
                                1439555627      ; Serial
                                10800           ; Refresh
                                3600            ; Retry
                                604800          ; Expire
                                3600)           ; Minimum
@                       NS      ns1.cybercity.dk.
@                       NS      ns2.cybercity.dk.
0                       PTR     0x55508a00.adsl.cybercity.dk.
1                       PTR     0x55508a01.adsl.cybercity.dk.
2                       PTR     0x55508a02.adsl.cybercity.dk.
3                       PTR     0x55508a03.adsl.cybercity.dk.

Starting import using: /home/pto/home/namedb/gen/test.conf
zone: 138.80.85.in-addr.arpa    from    gen/d6/P.138.80.85.in-addr.arpa_test
zid: 8752
NS : 138.80.85.in-addr.arpa     ns1.cybercity.dk.
NS : 138.80.85.in-addr.arpa     ns2.cybercity.dk.
NS : 138.80.85.in-addr.arpa     ns3.cybercity.dk.
NS : 138.80.85.in-addr.arpa     ns4.cybercity.dk.
PTR : 0.138.80.85.in-addr.arpa  0x55508a00.adsl.cybercity.dk
record exists
PTR : 1.138.80.85.in-addr.arpa  0x55508a01.adsl.cybercity.dk
0
                                  1    PTR        0x55508a01.adsl.cybercity.dk.
record exists
PTR : 2.138.80.85.in-addr.arpa  0x55508a02.adsl.cybercity.dk
0
                                  2    PTR        0x55508a02.adsl.cybercity.dk.
record exists
PTR : 3.138.80.85.in-addr.arpa  0x55508a03.adsl.cybercity.dk
0
                                  3    PTR        0x55508a03.adsl.cybercity.dk.
record exists

SQL data from zone nt_zone_record:

773909  8752    1   3600    NULL    12  0x55508a01.adsl.cybercity.dk.   NULL    NULL    NULL    NULL    NULL    0
774020  8752    2   3600    NULL    12  0x55508a02.adsl.cybercity.dk.   NULL    NULL    NULL    NULL    NULL    0
774087  8752    3   3600    NULL    12  0x55508a03.adsl.cybercity.dk.   NULL    NULL    NULL    NULL    NULL    0

The zone is not shown in nictool either.

**Comment by pertoft** [comment]
Looks like the "0" are cast to null

PTR : 0.138.80.85.in-addr.arpa  0x55508a00.adsl.cybercity.dk
$VAR1 = {
          '2_field' => 'type',
          '2_inclusive' => 'And',
          '2_option' => 'equals',
          '2_value' => 'PTR',
          '3_field' => 'address',
          '3_inclusive' => 'And',
          '3_option' => 'equals',
          '3_value' => '0x55508a00.adsl.cybercity.dk.',
          'Search' => 1,
          'limit' => 255,
          'nt_zone_id' => '8752'
        };
record exists
$VAR1 = [];
PTR : 1.138.80.85.in-addr.arpa  0x55508a01.adsl.cybercity.dk
$VAR1 = {
          '1_field' => 'name',
          '1_option' => 'equals',
          '1_value' => '1',
          '2_field' => 'type',
          '2_inclusive' => 'And',
          '2_option' => 'equals',
          '2_value' => 'PTR',
          '3_field' => 'address',
          '3_inclusive' => 'And',
          '3_option' => 'equals',
          '3_value' => '0x55508a01.adsl.cybercity.dk.',
          'Search' => 1,
          'limit' => 255,
          'nt_zone_id' => '8752'
        };


I suspeckt that the error is in forming request :

    my %request = (
        'nt_zone_id' => $p{zone_id},
        'Search'     => 1,
        limit        => 255,
    );

    if ( $p{name} ) {
        $request{'1_field'}  = 'name';
        $request{'1_option'} = 'equals';
        $request{'1_value'}  = $p{name};
    }

    if ( $p{type} ) {
        $request{'2_inclusive'} = 'And';
        $request{'2_field'}     = 'type';
        $request{'2_option'}    = 'equals';
        $request{'2_value'}     = $p{type};
    }

    if ( $p{address} ) {
        $request{'3_inclusive'} = 'And';
        $request{'3_field'}     = 'address';
        $request{'3_option'}    = 'equals';
        $request{'3_value'}     = $p{address};
    };

    warn Dumper(\%request);

**Comment by msimerson** [comment]
There seems to be a mismatch between `0.138.80.85.in-addr.arpa` and the zone detected:

````
Starting import using: /home/pto/home/namedb/gen/test.conf
zone: 138.80.85.in-addr.arpa from gen/d6/P.138.80.85.in-addr.arpa_test
zid: 8752
````

Are you importing from BIND?  If so, show the relevant portion of the named.conf file.

**Comment by pertoft** [comment]
Hi Matt,

I'm importing BIND zone files where the problem occurs.

The complete zone files below...

The record below is not impoted in nictool.
0                       PTR     0x55508a00.adsl.cybercity.dk.

I have also tested the TinyDNS import, and it imports the zone file correct.

Tell me if you need more.
Thanks,
Per

named.conf:
zone "138.80.85.in-addr.arpa" { type master; file "gen/d6/P.138.80.85.in-addr.arpa"; };


./gen/d6/P.138.80.85.in-addr.arpa:

; THIS FILE IS GENERATED, DO NOT EDIT
$TTL 3600
@               IN      SOA     ns1.cybercity.dk.       zonec.cybercity.dk. (
                                1441353524      ; Serial
                                10800           ; Refresh
                                3600            ; Retry
                                604800          ; Expire
                                3600)           ; Minimum
@                       NS      ns1.cybercity.dk.
@                       NS      ns2.cybercity.dk.
@                       NS      ns3.cybercity.dk.
@                       NS      ns4.cybercity.dk.
0                       PTR     0x55508a00.adsl.cybercity.dk.
1                       PTR     0x55508a01.adsl.cybercity.dk.
2                       PTR     0x55508a02.adsl.cybercity.dk.
3                       PTR     0x55508a03.adsl.cybercity.dk.
4                       PTR     0x55508a04.adsl.cybercity.dk.
5                       PTR     0x55508a05.adsl.cybercity.dk.
6                       PTR     0x55508a06.adsl.cybercity.dk.
7                       PTR     0x55508a07.adsl.cybercity.dk.
8                       PTR     0x55508a08.adsl.cybercity.dk.
9                       PTR     0x55508a09.adsl.cybercity.dk.
10                      PTR     0x55508a0a.adsl.cybercity.dk.
11                      PTR     0x55508a0b.adsl.cybercity.dk.
12                      PTR     0x55508a0c.adsl.cybercity.dk.
13                      PTR     0x55508a0d.adsl.cybercity.dk.
14                      PTR     0x55508a0e.adsl.cybercity.dk.
15                      PTR     0x55508a0f.adsl.cybercity.dk.
16                      PTR     0x55508a10.adsl.cybercity.dk.
17                      PTR     0x55508a11.adsl.cybercity.dk.
18                      PTR     0x55508a12.adsl.cybercity.dk.
19                      PTR     0x55508a13.adsl.cybercity.dk.
20                      PTR     0x55508a14.adsl.cybercity.dk.
21                      PTR     0x55508a15.adsl.cybercity.dk.
22                      PTR     0x55508a16.adsl.cybercity.dk.
23                      PTR     0x55508a17.adsl.cybercity.dk.
24                      PTR     0x55508a18.adsl.cybercity.dk.
25                      PTR     0x55508a19.adsl.cybercity.dk.
26                      PTR     0x55508a1a.adsl.cybercity.dk.
27                      PTR     0x55508a1b.adsl.cybercity.dk.
28                      PTR     0x55508a1c.adsl.cybercity.dk.
29                      PTR     0x55508a1d.adsl.cybercity.dk.
30                      PTR     0x55508a1e.adsl.cybercity.dk.
31                      PTR     0x55508a1f.adsl.cybercity.dk.
32                      PTR     0x55508a20.adsl.cybercity.dk.
33                      PTR     0x55508a21.adsl.cybercity.dk.
34                      PTR     0x55508a22.adsl.cybercity.dk.
35                      PTR     0x55508a23.adsl.cybercity.dk.
36                      PTR     0x55508a24.adsl.cybercity.dk.
37                      PTR     0x55508a25.adsl.cybercity.dk.
38                      PTR     0x55508a26.adsl.cybercity.dk.
39                      PTR     0x55508a27.adsl.cybercity.dk.
40                      PTR     0x55508a28.adsl.cybercity.dk.
41                      PTR     0x55508a29.adsl.cybercity.dk.
42                      PTR     0x55508a2a.adsl.cybercity.dk.
43                      PTR     0x55508a2b.adsl.cybercity.dk.
44                      PTR     0x55508a2c.adsl.cybercity.dk.
45                      PTR     0x55508a2d.adsl.cybercity.dk.
46                      PTR     0x55508a2e.adsl.cybercity.dk.
47                      PTR     0x55508a2f.adsl.cybercity.dk.
48                      PTR     0x55508a30.adsl.cybercity.dk.
49                      PTR     0x55508a31.adsl.cybercity.dk.
50                      PTR     0x55508a32.adsl.cybercity.dk.
51                      PTR     0x55508a33.adsl.cybercity.dk.
52                      PTR     0x55508a34.adsl.cybercity.dk.
53                      PTR     0x55508a35.adsl.cybercity.dk.
54                      PTR     0x55508a36.adsl.cybercity.dk.
55                      PTR     0x55508a37.adsl.cybercity.dk.
56                      PTR     0x55508a38.adsl.cybercity.dk.
57                      PTR     0x55508a39.adsl.cybercity.dk.
58                      PTR     0x55508a3a.adsl.cybercity.dk.
59                      PTR     0x55508a3b.adsl.cybercity.dk.
60                      PTR     0x55508a3c.adsl.cybercity.dk.
61                      PTR     0x55508a3d.adsl.cybercity.dk.
62                      PTR     0x55508a3e.adsl.cybercity.dk.
63                      PTR     0x55508a3f.adsl.cybercity.dk.
64                      PTR     0x55508a40.adsl.cybercity.dk.
65                      PTR     0x55508a41.adsl.cybercity.dk.
66                      PTR     0x55508a42.adsl.cybercity.dk.
67                      PTR     0x55508a43.adsl.cybercity.dk.
68                      PTR     0x55508a44.adsl.cybercity.dk.
69                      PTR     0x55508a45.adsl.cybercity.dk.
70                      PTR     0x55508a46.adsl.cybercity.dk.
71                      PTR     0x55508a47.adsl.cybercity.dk.
72                      PTR     0x55508a48.adsl.cybercity.dk.
73                      PTR     0x55508a49.adsl.cybercity.dk.
74                      PTR     0x55508a4a.adsl.cybercity.dk.
75                      PTR     0x55508a4b.adsl.cybercity.dk.
76                      PTR     0x55508a4c.adsl.cybercity.dk.
77                      PTR     0x55508a4d.adsl.cybercity.dk.
78                      PTR     0x55508a4e.adsl.cybercity.dk.
79                      PTR     0x55508a4f.adsl.cybercity.dk.
80                      PTR     0x55508a50.adsl.cybercity.dk.
81                      PTR     0x55508a51.adsl.cybercity.dk.
82                      PTR     0x55508a52.adsl.cybercity.dk.
83                      PTR     0x55508a53.adsl.cybercity.dk.
84                      PTR     0x55508a54.adsl.cybercity.dk.
85                      PTR     0x55508a55.adsl.cybercity.dk.
86                      PTR     0x55508a56.adsl.cybercity.dk.
87                      PTR     0x55508a57.adsl.cybercity.dk.
88                      PTR     0x55508a58.adsl.cybercity.dk.
89                      PTR     0x55508a59.adsl.cybercity.dk.
90                      PTR     0x55508a5a.adsl.cybercity.dk.
91                      PTR     0x55508a5b.adsl.cybercity.dk.
92                      PTR     0x55508a5c.adsl.cybercity.dk.
93                      PTR     0x55508a5d.adsl.cybercity.dk.
94                      PTR     0x55508a5e.adsl.cybercity.dk.
95                      PTR     0x55508a5f.adsl.cybercity.dk.
96                      PTR     0x55508a60.adsl.cybercity.dk.
97                      PTR     0x55508a61.adsl.cybercity.dk.
98                      PTR     0x55508a62.adsl.cybercity.dk.
99                      PTR     0x55508a63.adsl.cybercity.dk.
100                     PTR     0x55508a64.adsl.cybercity.dk.
101                     PTR     0x55508a65.adsl.cybercity.dk.
102                     PTR     0x55508a66.adsl.cybercity.dk.
103                     PTR     0x55508a67.adsl.cybercity.dk.
104                     PTR     0x55508a68.adsl.cybercity.dk.
105                     PTR     0x55508a69.adsl.cybercity.dk.
106                     PTR     0x55508a6a.adsl.cybercity.dk.
107                     PTR     0x55508a6b.adsl.cybercity.dk.
108                     PTR     0x55508a6c.adsl.cybercity.dk.
109                     PTR     0x55508a6d.adsl.cybercity.dk.
110                     PTR     0x55508a6e.adsl.cybercity.dk.
111                     PTR     0x55508a6f.adsl.cybercity.dk.
112                     PTR     0x55508a70.adsl.cybercity.dk.
113                     PTR     0x55508a71.adsl.cybercity.dk.
114                     PTR     0x55508a72.adsl.cybercity.dk.
115                     PTR     0x55508a73.adsl.cybercity.dk.
116                     PTR     0x55508a74.adsl.cybercity.dk.
117                     PTR     0x55508a75.adsl.cybercity.dk.
118                     PTR     0x55508a76.adsl.cybercity.dk.
119                     PTR     0x55508a77.adsl.cybercity.dk.
120                     PTR     0x55508a78.adsl.cybercity.dk.
121                     PTR     0x55508a79.adsl.cybercity.dk.
122                     PTR     0x55508a7a.adsl.cybercity.dk.
123                     PTR     0x55508a7b.adsl.cybercity.dk.
124                     PTR     0x55508a7c.adsl.cybercity.dk.
125                     PTR     0x55508a7d.adsl.cybercity.dk.
126                     PTR     0x55508a7e.adsl.cybercity.dk.
127                     PTR     0x55508a7f.adsl.cybercity.dk.
128                     PTR     0x55508a80.adsl.cybercity.dk.
129                     PTR     0x55508a81.adsl.cybercity.dk.
130                     PTR     0x55508a82.adsl.cybercity.dk.
131                     PTR     0x55508a83.adsl.cybercity.dk.
132                     PTR     0x55508a84.adsl.cybercity.dk.
133                     PTR     0x55508a85.adsl.cybercity.dk.
134                     PTR     0x55508a86.adsl.cybercity.dk.
135                     PTR     0x55508a87.adsl.cybercity.dk.
136                     PTR     0x55508a88.adsl.cybercity.dk.
137                     PTR     0x55508a89.adsl.cybercity.dk.
138                     PTR     0x55508a8a.adsl.cybercity.dk.
139                     PTR     0x55508a8b.adsl.cybercity.dk.
140                     PTR     0x55508a8c.adsl.cybercity.dk.
141                     PTR     0x55508a8d.adsl.cybercity.dk.
142                     PTR     0x55508a8e.adsl.cybercity.dk.
143                     PTR     0x55508a8f.adsl.cybercity.dk.
144                     PTR     0x55508a90.adsl.cybercity.dk.
145                     PTR     0x55508a91.adsl.cybercity.dk.
146                     PTR     0x55508a92.adsl.cybercity.dk.
147                     PTR     0x55508a93.adsl.cybercity.dk.
148                     PTR     0x55508a94.adsl.cybercity.dk.
149                     PTR     0x55508a95.adsl.cybercity.dk.
150                     PTR     0x55508a96.adsl.cybercity.dk.
151                     PTR     0x55508a97.adsl.cybercity.dk.
152                     PTR     0x55508a98.adsl.cybercity.dk.
153                     PTR     0x55508a99.adsl.cybercity.dk.
154                     PTR     0x55508a9a.adsl.cybercity.dk.
155                     PTR     0x55508a9b.adsl.cybercity.dk.
156                     PTR     0x55508a9c.adsl.cybercity.dk.
157                     PTR     0x55508a9d.adsl.cybercity.dk.
158                     PTR     0x55508a9e.adsl.cybercity.dk.
159                     PTR     0x55508a9f.adsl.cybercity.dk.
160                     PTR     0x55508aa0.adsl.cybercity.dk.
161                     PTR     0x55508aa1.adsl.cybercity.dk.
162                     PTR     0x55508aa2.adsl.cybercity.dk.
163                     PTR     0x55508aa3.adsl.cybercity.dk.
164                     PTR     0x55508aa4.adsl.cybercity.dk.
165                     PTR     0x55508aa5.adsl.cybercity.dk.
166                     PTR     0x55508aa6.adsl.cybercity.dk.
167                     PTR     0x55508aa7.adsl.cybercity.dk.
168                     PTR     0x55508aa8.adsl.cybercity.dk.
169                     PTR     0x55508aa9.adsl.cybercity.dk.
170                     PTR     0x55508aaa.adsl.cybercity.dk.
171                     PTR     0x55508aab.adsl.cybercity.dk.
172                     PTR     0x55508aac.adsl.cybercity.dk.
173                     PTR     0x55508aad.adsl.cybercity.dk.
174                     PTR     0x55508aae.adsl.cybercity.dk.
175                     PTR     0x55508aaf.adsl.cybercity.dk.
176                     PTR     0x55508ab0.adsl.cybercity.dk.
177                     PTR     0x55508ab1.adsl.cybercity.dk.
178                     PTR     0x55508ab2.adsl.cybercity.dk.
179                     PTR     0x55508ab3.adsl.cybercity.dk.
180                     PTR     0x55508ab4.adsl.cybercity.dk.
181                     PTR     0x55508ab5.adsl.cybercity.dk.
182                     PTR     0x55508ab6.adsl.cybercity.dk.
183                     PTR     0x55508ab7.adsl.cybercity.dk.
184                     PTR     0x55508ab8.adsl.cybercity.dk.
185                     PTR     0x55508ab9.adsl.cybercity.dk.
186                     PTR     0x55508aba.adsl.cybercity.dk.
187                     PTR     0x55508abb.adsl.cybercity.dk.
188                     PTR     0x55508abc.adsl.cybercity.dk.
189                     PTR     0x55508abd.adsl.cybercity.dk.
190                     PTR     0x55508abe.adsl.cybercity.dk.
191                     PTR     0x55508abf.adsl.cybercity.dk.
192                     PTR     0x55508ac0.adsl.cybercity.dk.
193                     PTR     0x55508ac1.adsl.cybercity.dk.
194                     PTR     0x55508ac2.adsl.cybercity.dk.
195                     PTR     0x55508ac3.adsl.cybercity.dk.
196                     PTR     0x55508ac4.adsl.cybercity.dk.
197                     PTR     0x55508ac5.adsl.cybercity.dk.
198                     PTR     0x55508ac6.adsl.cybercity.dk.
199                     PTR     0x55508ac7.adsl.cybercity.dk.
200                     PTR     0x55508ac8.adsl.cybercity.dk.
201                     PTR     0x55508ac9.adsl.cybercity.dk.
202                     PTR     0x55508aca.adsl.cybercity.dk.
203                     PTR     0x55508acb.adsl.cybercity.dk.
204                     PTR     0x55508acc.adsl.cybercity.dk.
205                     PTR     0x55508acd.adsl.cybercity.dk.
206                     PTR     0x55508ace.adsl.cybercity.dk.
207                     PTR     0x55508acf.adsl.cybercity.dk.
208                     PTR     0x55508ad0.adsl.cybercity.dk.
209                     PTR     0x55508ad1.adsl.cybercity.dk.
210                     PTR     0x55508ad2.adsl.cybercity.dk.
211                     PTR     0x55508ad3.adsl.cybercity.dk.
212                     PTR     0x55508ad4.adsl.cybercity.dk.
213                     PTR     0x55508ad5.adsl.cybercity.dk.
214                     PTR     0x55508ad6.adsl.cybercity.dk.
215                     PTR     0x55508ad7.adsl.cybercity.dk.
216                     PTR     0x55508ad8.adsl.cybercity.dk.
217                     PTR     0x55508ad9.adsl.cybercity.dk.
218                     PTR     0x55508ada.adsl.cybercity.dk.
219                     PTR     0x55508adb.adsl.cybercity.dk.
220                     PTR     0x55508adc.adsl.cybercity.dk.
221                     PTR     0x55508add.adsl.cybercity.dk.
222                     PTR     0x55508ade.adsl.cybercity.dk.
223                     PTR     0x55508adf.adsl.cybercity.dk.
224                     PTR     0x55508ae0.adsl.cybercity.dk.
225                     PTR     0x55508ae1.adsl.cybercity.dk.
226                     PTR     0x55508ae2.adsl.cybercity.dk.
227                     PTR     0x55508ae3.adsl.cybercity.dk.
228                     PTR     0x55508ae4.adsl.cybercity.dk.
229                     PTR     0x55508ae5.adsl.cybercity.dk.
230                     PTR     0x55508ae6.adsl.cybercity.dk.
231                     PTR     0x55508ae7.adsl.cybercity.dk.
232                     PTR     0x55508ae8.adsl.cybercity.dk.
233                     PTR     0x55508ae9.adsl.cybercity.dk.
234                     PTR     0x55508aea.adsl.cybercity.dk.
235                     PTR     0x55508aeb.adsl.cybercity.dk.
236                     PTR     0x55508aec.adsl.cybercity.dk.
237                     PTR     0x55508aed.adsl.cybercity.dk.
238                     PTR     0x55508aee.adsl.cybercity.dk.
239                     PTR     0x55508aef.adsl.cybercity.dk.
240                     PTR     0x55508af0.adsl.cybercity.dk.
241                     PTR     0x55508af1.adsl.cybercity.dk.
242                     PTR     0x55508af2.adsl.cybercity.dk.
243                     PTR     0x55508af3.adsl.cybercity.dk.
244                     PTR     0x55508af4.adsl.cybercity.dk.
245                     PTR     0x55508af5.adsl.cybercity.dk.
246                     PTR     0x55508af6.adsl.cybercity.dk.
247                     PTR     0x55508af7.adsl.cybercity.dk.
248                     PTR     0x55508af8.adsl.cybercity.dk.
249                     PTR     0x55508af9.adsl.cybercity.dk.
250                     PTR     0x55508afa.adsl.cybercity.dk.
251                     PTR     0x55508afb.adsl.cybercity.dk.
252                     PTR     0x55508afc.adsl.cybercity.dk.
253                     PTR     0x55508afd.adsl.cybercity.dk.
254                     PTR     0x55508afe.adsl.cybercity.dk.
255                     PTR     0x55508aff.adsl.cybercity.dk.
