### ISSUE TITLE
Adding an incorrect new RR via webgui can produce a faulty form

### ISSUE THREAD

**Issue by rduffner** [msimerson/NicTool#104]
Earlier today, I noticed a funny thing:
In the webgui, if I add a new record to a domain, it sort-of pre-populates the fields with useful values. But these values aren't actually there (they're greyed out).
So, if you submit the form (e.g. for an MX record), it will complain.
At least for the MX record I found that the form you get back misses the "weight" field.
So if you try to submit that form, it will (rightfully) complain about the missing weight...

**Comment by msimerson** [comment]
> it sort-of pre-populates the fields with useful values.

Those are HTML 5 placeholder tags. They provide some "suggestions" for what type of value might belong there.

> So, if you submit the form (e.g. for an MX record), it will complain.
> At least for the MX record I found that the form you get back misses the "weight" field.

Hrmm yeah. Likely a JS bug that needs attention.

**Comment by rduffner** [comment]
I figured it were suggestions - I just stumbled on the form without the weight field (haven't added an MX in the GUI for a while). It would complain about the missing weight over and over again and I tried to figure out a way to add it to one of the other fields...
