### ISSUE TITLE
create_tables.pl broken 

### ISSUE THREAD

**Issue by ethanmullins** [msimerson/NicTool#107]
While running the create_tables perl script on Freebsd 10, it errors out with "/usr/local/lib/perl5/site_perl/mach/5.20/auto/DBD/mysql/mysql.so: Undefined symbol "mysql_options4" "

**Comment by msimerson** [comment]
That's saying that your perl / mysql (think: DBI / DBD layer) is broken. Reinstall p5-DBD-mysql and that should solve your problem.
