### ISSUE TITLE
Download Nictool from tnpi.net error 404

### ISSUE THREAD

**Issue by BaVanDuong** [msimerson/NicTool#108]
Hello,
I install flow your document but when download source from https://www.tnpi.net/cart/index.php/downloads error 404. 
Then i cloned from github but not found file Makefile.PL in directory "client" and "server". Some thing wrong in my steps?

**Comment by msimerson** [comment]
Sorry, fixed. I broke that after switching web servers (to nginx) and didn't have SEO friendly URLs configured.

**Comment by BaVanDuong** [comment]
Hello,
Thank you. It worked.
