### ISSUE TITLE
nt_export.pl errors

### ISSUE THREAD

**Issue by ShaunR** [msimerson/NicTool#109]
```
[root@server exporter-nsid-1]# setuidgid nictool ../server/bin/nt_export.pl -nsid 1
Use of uninitialized value $dir in concatenation (.) or string at ../server/bin/nt_export.pl line 32.
Use of uninitialized value $LIB_DIR in substitution (s///) at ../server/bin/nt_export.pl line 46.
Use of uninitialized value $prog_dir in substitution (s///) at ../server/bin/nt_export.pl line 168.
Use of uninitialized value $prog_dir in concatenation (.) or string at ../server/bin/nt_export.pl line 173.
nsid 1 has xxxxx zones, 0 changed, exiting
```

My run file looks as follows

```
#!/bin/sh
exec 2>&1
cd /usr/local/nictool/exporter-nsid-1
EXPORT_USER=nictool
exec setuidgid $EXPORT_USER ../server/bin/nt_export.pl -nsid 1 -daemon -pfextra | logger
cd -
```

The issue has to do with `@PATH` having a undef value inside it which was set earlier in the script with push

```
push @PATH, '.', undef;
```

If i hard code the nt_export.pl path in the run file I do not get these errors.  It looks like your attempting to do some magic with env $PATH to figure out where the script is to set lib paths?  The script only looks to do this magic if $0 does not start with /.  So unless an absolute path is set, the issue shows up.

Have not come up with a workaround yet, haven't had time.

**Comment by msimerson** [comment]
Yeah, that change came in #68 and it looks to me like pushing an undef onto PATH is an error. Maybe it does something magical, but I suspect not and I'd be tempted to remove it, or replace it with an empty string. Maybe @hickey can comment on his intent there.

**Comment by ShaunR** [comment]
I had the same thought and I removed it as well as set an empty string.  Both caused other issues.

I feel like the path should just be hard coded into that script when nictool is built.  NicTool is a bit weird though with how it installs itself like a normal module would, yet we still have it installed in another location.  Have you ever though about making nictool a standalone piece of software with a configure and make script?  This would allow for ```--prefix``` to be used to set install locations and all of nictool could reside in one location.

**Comment by msimerson** [comment]
PRs are welcome.

**Comment by hickey** [comment]
Sorry, I have been busy and traveling for a while. Shame on me for not paying attention to Github!

Looking back at the auto location code, I agree that the undef does not need to be there. The original code I wrote for another project would append more directories during the search and so there was a need to mark the end of the original list of directories. That is what undef did for me. In this context, it is not needed and I can see where it could cause additional errors.

Looking back at the code and thinking about it, there should probably a check to insure that $PROG_LOCATION has a value.
