### ISSUE TITLE
NicToolClient.pm has version 2.31

### ISSUE THREAD

**Issue by ShaunR** [msimerson/NicTool#110]
I'm assuming your trying to keep the Server and Client versions inline?  If so, NicTool 2.32 comes with the client showing version 2.31

**Comment by msimerson** [comment]
They are separate packages with separate versions for a reason. Often times, there's no reason to change one. ;-)

**Comment by ShaunR** [comment]
Question really is going to eventually be, how do you know what client version is compatible with what server version.  What happens if/when the server version is 2.54 and the client version is 2.81?  It's going to be real confusing. Seams like these go hand and hand and should probably just stay in sync with each other?  

This also kind of relates to my other comment on a earlier issue were i talked about maybe nictool needing to be a single software. just some thoughts of mine :)
