### ISSUE TITLE
prerequisite not found

### ISSUE THREAD

**Issue by mokeli** [msimerson/NicTool#120]
Hi, i have followed you install the dependencies that requires but while
perl Makefile.PL
there are a lot of warning return to me.

Warning: prerequisite APR::Table 0 not found.
Warning: prerequisite BIND::Conf_Parser 0 not found.
Warning: prerequisite Crypt::KeyDerivation 0 not found.
Warning: prerequisite Crypt::Mac::HMAC 0 not found.
Warning: prerequisite CryptX 0.021 not found.
Warning: prerequisite DBIx::Simple 0 not found.
Warning: prerequisite JSON 0 not found.
Warning: prerequisite MIME::Base32 0 not found.
Warning: prerequisite Net::DNS::Zone::Parser 0 not found.
Warning: prerequisite Params::Validate 0.8 not found.
Warning: prerequisite RPC::XML 0 not found.
Warning: prerequisite RPC::XML::Parser 0 not found.
Warning: prerequisite SOAP::Lite 0.51 not found.
Warning: prerequisite Time::TAI64 2 not found.
Warning: prerequisite XML::Parser 0 not found.
Warning: prerequisite mod_perl 0 not found.
Warning: prerequisite RPC::XML 1 not found.
Warning: prerequisite RPC::XML::Parser 0 not found.
Warning: prerequisite SOAP::Lite 0.51 not found.
Warning: prerequisite TestConfig 0 not found.
Writing Makefile for NicTool
Writing MYMETA.yml and MYMETA.json
Writing Makefile for NicToolServer
Writing MYMETA.yml and MYMETA.json

but is actually the problems? can anyone tell me please, even i had tried install
perl -MCPAN -e shell
cpan> install SOAP::Lite
cpan> install DBI
cpan> install DBD::mysql
cpan> install Apache2::SOAP
cpan> install Apache::DBI
cpan> install Net::IP

Thanks

**Comment by msimerson** [comment]
There are several sets of documentation for installing in various environments. Please specify exactly which instructions you were following.

**Comment by mokeli** [comment]
Cuurently im install it on the Ubuntu 14.04 LTS
anoother link to refer is : http://blackonsole.org/install-nictool-on-linux-debian/

**Comment by msimerson** [comment]
Use the Ubuntu instructions [published here](https://github.com/msimerson/NicTool/wiki/Install-NicTool-on-Ubuntu) on the GitHub Wiki instead. I built a system on Ubuntu last week. If you have issues, post a link to a gist of your install session.
