### ISSUE TITLE
Usage of remote_login in export to powerdns would be nice

### ISSUE THREAD

**Issue by Popyllol** [msimerson/NicTool#121]
Hey crew,
it looks like the DB-Field remote_login for the rsync/ssh connection in export is not used in powerdns-export (or maybe only in tinydns-export?).
Would be nice to have it usable in all rsync/ssh-related exports.
Thank you!
   Lars

**Comment by ShaunR** [comment]
I'm the one who fixed this issue for tinydns a while back and can confirm that the logic for remote_login is missing from the PowerDNS module.  I've created a pull request to correct it.

I have not tested the code, @Popyllol you want to give it a go?

**Comment by ShaunR** [comment]
I've updated my PR to fix this issue on PowerDNS, Knot, and NSD

**Comment by Popyllol** [comment]
Great! That was fast!
Thank you Shaun!
I will try it out the next days and will let you know.

**Comment by ShaunR** [comment]
@Popyllol I was the one who fixed this issue with tinydns so it was an easy fix when i saw the issue pop up. We just need to wait for @msimerson now to accept my PR

**Comment by msimerson** [comment]
Fixed by #122

**Comment by Popyllol** [comment]
Sorry for the late reply...
I can confirm that the fix works for me!
Thank you for the fast fix!
