### ISSUE TITLE
Allowing NS records even though nameserver do not exit?

### ISSUE THREAD

**Issue by ShaunR** [msimerson/NicTool#132]
I'm importing records from bind servers into NicTool using a export/sync script i wrote.  The issue I just encountered is that when trying to pull over ```IN NS``` records for nameservers that NicTool does not know about it gets angry.  NicTool wants those nameservers to exist in the nameservers section.  Should we be forcing this?  I've had situations where a customer is using our nameservers as well as their own.

**Comment by msimerson** [comment]
What version of NicTool are you running? I think we've relaxed that requirement in the source, but that change hasn't been pushed out as a new release. Yet.

**Comment by ShaunR** [comment]
2.33 just upgraded the other day.

**Comment by msimerson** [comment]
Right, but I think that change was committed after 2.33 was released.

**Comment by ShaunR** [comment]
Was it a large commit or something i can modify on my install easily? Do you have a link to that change?

**Comment by ShaunR** [comment]
Think i may of found it...

https://github.com/msimerson/NicTool/commit/445199884d72afcc702ca779921ae3290ad4321e

**Comment by ShaunR** [comment]
Nope, that commit already exists on my install.

**Comment by msimerson** [comment]
Okay, ignore me then. I haven't paid NicTool much attention recently.

**Comment by ShaunR** [comment]
The issue looks to be in lib/NicToolServer/Zone/Record.pm on line 78

Looking at the code i'm sure i can easily bypass this, however... There is some code that checks to see if the user is allowed to use a nameserver that exists within nictool. Not sure if that's really all that important.

Digging further i see that nictool does some relationship stuff when adding NS records.  Looks like it replaces a row in nt_zone_nameserver linking the nt_nameserver_id to the nt_zone_id.

Thinking about this further i wonder if the solution here would be to check if the nameserver exists, if it does check permissions, and then run the second add_zone_nameserver function.  If the nameserver doesnt exist then simply skip all that.

I really dont know enough about nictool's backend to know if this would cause any issues.

**Comment by ShaunR** [comment]
Closing this for now.  I may work on these modifications but it's going to probably take a while and test and I don't have the time to do this now.

@msimerson How's nictool, are you going to continue working on this project or...?

**Comment by msimerson** [comment]
Yes, I continue to work on NicTool when it has need and when I have time for it.
