### ISSUE TITLE
Fix for tinydns import of type 16 (TXT) generic records

### ISSUE THREAD

**Issue by ispcolohost** [msimerson/NicTool#134]
The tinydns.pm handles generic records of type 16 (TXT) with:

    if ($n == 16) {
        $r =~ s/:16//;
        return $self->zr_txt( $r );
    };

but the second line in the above code should be:

        $r =~ s/:16:\\\d\d\d/:/;

The explanation for this is that a properly encoded TXT record entered as a tinydns generic will have its rdata prefixed by an octal-format number indicating the byte count of the record.  This is necessary because the definition of a TXT record requires the first byte served be the length of the coming record.  For example, if you wanted to serve a TXT record of `"abcd:abcd:abcd:abcd:abcd:abcd:123"` then your record is going to be 33 characters in length, and the tinydns format generic will look like this:

`:domain.com:16:\041abcd\072abcd\072abcd\072abcd\072abcd\072abcd\072123:`

where \041 is decimal 33 in octal form, followed by the record with the relevant escape sequences substituted for the colon.  Nictool will end up importing this record as:

`!abcd:abcd:abcd:abcd:abcd:abcd:123`

because \041 is ! in ascii.

**Comment by msimerson** [comment]
>  will have its rdata prefixed by an octal-format number indicating the byte count of the record.

Agreed.

> but the second line in the above code should be:
>
>    `$r =~ s/:16:\\\d\d\d/:/;`

That's an improvement, but I think that may fail in another way. What happens when the character count of the TXT entry exceeds 511 characters? (seems inevitable...)

````
perl -e "printf '\%03lo', 512"
\1000
````

I can't think of a case where this regex would fail, can you?

```perl
$r =~ s/:16:\\[\d]{3,}/:/;
```

**Comment by ispcolohost** [comment]
I agree on that fix.  For the sake of argument though, a TXT record, by definition, is not supposed to be larger than 255 characters, and even if you ignore that, a UDP packet in DNS is 512 bytes max, so given the requirement of a TXT record to lead with the byte count, it should not be possible to serve a TXT record that is 512 characters or larger.  Nictool should probably ignore/error/discard such a record even though the importer could potentially load them using the improved regex.

**Comment by msimerson** [comment]
> TXT record, by definition, is not supposed to be larger than 255 characters

That's a common misreading of the RFC. The 255 character limit for TXT records is for the maximum _string_ length. TXT records can and frequently are (example: 2048 bit DKIM keys) composed of multiple strings which get concatenated. 

> a UDP packet in DNS is 512 bytes max

Which is why (and axfr) TCP for DNS exists. Longer TXT records are already in common use on the internet, for both DKIM public keys and SPF records.

**Comment by msimerson** [comment]
from RFC 1035:

````
3.3.14. TXT RDATA format

    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
    /                   TXT-DATA                    /
    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+

where:

TXT-DATA        One or more <character-string>s.

TXT RRs are used to hold descriptive text.  The semantics of the text
depends on the domain where it is found.
````

**Comment by msimerson** [comment]
Drive-by anecdote: this week someone imported (to NicTool, from tinydns) a 850 character SPF record.
