### ISSUE TITLE
Base.pm issue with $p{contact}

### ISSUE THREAD

**Issue by ispcolohost** [msimerson/NicTool#141]
This line can be problematic:

$p{contact} =~ s/@/./g;  # clean up common format error in mailaddr string

because there's no default value for contact and it's not a mandatory field, so it may not exist.

Ran into this when importing tinydns zone files where the PTR zones are defined in a file differently from where the import encounters an = and tries to auto create a PTR zone.

**Comment by msimerson** [comment]
The fact that it's undefined usually isn't a problem in perl:

````
perl -e 'my $f; $f =~ s/@/\./g; print $f;'
````

Please provide more details, and preferably, a Pull Request with a test that exercises the problem with the existing code and passes tests with your fix (I presume wrapping that line with an `if $p{contact}`.

**Comment by msimerson** [comment]
Closing due to non-response. If this is still a problem for you, please follow up with a PR.
