### ISSUE TITLE
Changing TTL of an RRset

### ISSUE THREAD

**Issue by he32** [msimerson/NicTool#142]
Hi,

RFC 2181 mandates that all RRs which make up an RRset (same name, class & type)
must have the same TTL.  This of course makes sense.  However, the user interface of
nictool does not readily make it possible for a user to change the TTL of all RRs which make
up an RRset, and if the user tries to change the TTL of one of them, he's met with a flat rejection
pointing to RFC 2181.

There is a workaround for this issue, but it involves temporarily paring the RRset down to
just one RR by deleting the other RRs, changing the TTL of the now single RR, and
subsequently re-registering all the RRs to complete the RRset, this time with the new TTL.
The workaround is not exactly immediately intuitive...

It would be mcuh better if nictool offered as an optional action to change the TTL of all the
RRs which make up the RRset instead of flatly refusing to cooperate.

Ref. posting to list@nictool.com by my colleague Vegard.

Regards,

- Håvard

**Comment by msimerson** [comment]
PRs welcome.

**Comment by he32** [comment]
Not sure I understand, I thought that was what the above was...

**Comment by msimerson** [comment]
fixed by #157
