### ISSUE TITLE
Allow sub-domain creation in different group?

### ISSUE THREAD

**Issue by ispcolohost** [msimerson/NicTool#145]
Hello, I'm wondering if there's a way to allow for API-based subdomain creation across groups?

For example, in my case, I have groups Critical and Production.  There are group-specific users defined in each group.  The purpose of the Critical group is to hold zones which I do not want our regular staff being able to modify.  So staff who have nictool access for the purpose of production DNS chnages, do so via users defined in the Production group, but they can't see or touch zones in the Critical group.

The issue I'm running into is if domain.com is defined in Critical, staff in the Production group are not permitted to create subdomains like subdomain.domain.com in the Production group, even if no such record exists in domain.com:

Sub-domain creation not allowed: Access to zone domain.com denied: No Access Allowed to that object (ZONE : 21417)

Is there a way around this that would still be able to protect the zones I care about not granting staff access to?

**Comment by ShaunR** [comment]
I could see where this could be useful, but at the same time i could see where this could be a possible security concern too.  Lets say customerA in GroupA has their domain CustomerA.com, and then somebody in CustomerB/GroupB decides to add secure.CustomerA.com to their group.  Now CustomerB has contro over that sub domain!

**Comment by msimerson** [comment]
> Is there a way around this that would still be able to protect the zones I care about not granting staff access to?

Short answer: no.

The second you permit a party to create subdomains (zones) inside your zone, you've permitted them to override and delegate any and perhaps all records in that zone. Imagine the fun they could have when they published a subdomain in your zone named `*`. 

The only reasonable way to permit this type of use is to create the sub-domain in that critical domain and then delegate it tot he production group.
