### ISSUE TITLE
Sub-groups delegated name-server as parent group user when creating new zone

### ISSUE THREAD

**Issue by EwaldvanGeffen** [msimerson/NicTool#154]
### NicTool version
2.33

### Expected behavior
Creating a new zone as user of parent-zone-group I expect to only be able to select allowed name-server for this child zone-group.
### Observed behavior
All name-servers are selectedable, it seems to name-server selection follows the user-groups permissions over the zone in which you are trying to create the group.
### Steps to reproduce
be root
create ns1 in root-group nictool
create ns2 in root-group nictool
create zone in group nictool select ns1, ns2 -> OK
create subgroup child in nictool
allow ns1 to child
create new zone 
able to select ns1, ns2 -> should only be NS1

This option is really a choice, I can see circumstances where this can be useful however the child group user objects shouldn't be able in that case to modify that particular name-server selection.

**Comment by msimerson** [comment]
I use groups all the time for zones I want to be, ahem, grouped, but those groups don't necessarily have a NS in them. It would be awfully inconvenient if the NS I had permission to (in higher level groups) weren't available.

As you allude to, this is a choice. I call it a feature. ;-)  However, I would accept a PR that changes only NicToolClient and deselects the higher level NS when a group a zone is being created in has NS records of its own. That's a reasonable default and if a user has permission and wants to also publish to another NS, they still have the choice.
