### ISSUE TITLE
Duplicate new_zone_record AAAA responds 200 OK

### ISSUE THREAD

**Issue by c1784497** [msimerson/NicTool#160]
A new_zone_record call for an AAAA record can be repeated multiple times without a "Duplicate Resource Records" error being raised. The AAAA record is also inserted in the database multiple times.

### NicTool version
2.33
### perl version
5.18.2-2ubuntu1.1
### OS version
Ubuntu 14.04.5
### Expected behavior
`<?xml version="1.0" encoding="UTF-8"?><soap:Envelope soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:apachens="http://xml.apache.org/xml-soap" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soap:Body><new_zone_recordResponse xmlns="http://api.example.com/NicToolServer/SOAP"><s-gensym210><error_desc xsi:type="xsd:string">Sanity error</error_desc><error_msg xsi:type="xsd:string">Duplicate Resource Records are not allowed: RFC 2181</error_msg><error_code xsi:type="xsd:int">300</error_code><sanity_msg soapenc:arrayType="xsd:string[1]" xsi:type="soapenc:Array"><item xsi:type="xsd:string">Duplicate Resource Records are not allowed: RFC 2181</item></sanity_msg><sanity_err><name xsi:type="xsd:int">1</name></sanity_err></s-gensym210></new_zone_recordResponse></soap:Body></soap:Envelope>`
### Observed behavior
`<?xml version="1.0" encoding="UTF-8"?><soap:Envelope soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:apachens="http://xml.apache.org/xml-soap" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soap:Body><new_zone_recordResponse xmlns="http://api.example.com/NicToolServer/SOAP"><s-gensym201><error_msg xsi:type="xsd:string">OK</error_msg><nt_zone_record_id xsi:type="xsd:int">365</nt_zone_record_id><error_code xsi:type="xsd:int">200</error_code></s-gensym201></new_zone_recordResponse></soap:Body></soap:Envelope>`
### Steps to reproduce
Repeating this new_zone_record call:
`<?xml version="1.0" encoding="UTF-8"?><soap:Envelope soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soap:Body><new_zone_record xmlns="http://api.example.com/NicToolServer/SOAP"><c-gensym270><weight xsi:type="xsd:string" /><other xsi:type="xsd:string" /><location xsi:type="xsd:string" /><nt_zone_id xsi:type="xsd:int">18</nt_zone_id><type xsi:type="xsd:string">AAAA</type><name xsi:type="xsd:string">test</name><priority xsi:type="xsd:string" /><nt_group_id xsi:type="xsd:int">2</nt_group_id><ttl xsi:type="xsd:int">86400</ttl><nt_protocol_version xsi:type="xsd:float">1.0</nt_protocol_version><description xsi:type="xsd:string" /><nt_user_session xsi:type="xsd:string">xxxxxxxxxxxxxxxx</nt_user_session><address xsi:type="xsd:string">2000:1234:5000:0000:0000:0000:0000:1</address></c-gensym270></new_zone_record></soap:Body></soap:Envelope>`

**Comment by msimerson** [comment]
> The AAAA record is also inserted in the database multiple times.

Could you include the SQL results as well, showing the duplicated records?

**Comment by c1784497** [comment]
`INSERT INTO `nt_zone_record` (`nt_zone_record_id`, `nt_zone_id`, `name`, `ttl`, `description`, `type_id`, `address`, `weight`, `priority`, `other`, `location`, `timestamp`, `deleted`) VALUES
(363, 18, 'test', 86400, NULL, 28, '2000:1234:8000:0000:0000:0000:0000:0001', NULL, NULL, NULL, NULL, NULL, 0),
(365, 18, 'test', 86400, NULL, 28, '2000:1234:8000:0000:0000:0000:0000:0001', NULL, NULL, NULL, NULL, NULL, 0),
(367, 18, 'test', 86400, NULL, 28, '2000:1234:8000:0000:0000:0000:0000:0001', NULL, NULL, NULL, NULL, NULL, 0);`

**Comment by msimerson** [comment]
Pooh, that's not supposed to happen. 😞

**Comment by msimerson** [comment]
I read through the code a couple times, to make sure I wasn't insane, because it sure LOOKS like the code is going to perform the duplicate tests.  So then I attempted to replicate this on my NicTool install and, it does yield a duplicate error:

<img width="541" alt="screen shot 2017-03-13 at 10 42 45 am" src="https://cloud.githubusercontent.com/assets/261635/23867664/e03cf906-07d9-11e7-8302-dfba7ab72d4c.png">

**Comment by c1784497** [comment]
Please try with 2000:1234:8000:0000:0000:0000:0000:1

**Comment by msimerson** [comment]
Ahah, that's where the problem is. 

NicTool stores the AAAA addresses in expanded format, mostly because that's the only bulletproof way to compare them (there's a number of algorithms for compressing AAAA, all are legit). So AAAA operations just need to have the AAAA address expanded **before** the duplicate check.
