### ISSUE TITLE
Getting "Undefined subroutine CGI::multi_param" after upgrade to 2.34

### ISSUE THREAD

**Issue by rainerduffner** [msimerson/NicTool#174]
### NicTool version
2.34
### perl version
v5.24.1
### OS version
FreeBSD 11.0
### Expected behavior
worked before

### Observed behavior
after upgrade to 2.34, I can't add zones anymore

### Steps to reproduce
I've got the following perl modules installed:

p5-Apache-DBI-1.12_2           DBI persistent connection, authentication and authorization
p5-Authen-NTLM-1.09_1          Perl5 NTLM authentication module
p5-Authen-SASL-2.16_1          Perl5 module for SASL authentication
p5-BIND-Conf_Parser-0.95_1     Perl5 module to parse BIND 8 configuration files
p5-BSD-Resource-1.2907_1       Perl module to access BSD resource limit and priority functions
p5-CGI.pm-3.63_1,1             Simple Common Gateway Interface Class for Perl
p5-Class-Inspector-1.31        Provides information about classes
p5-Convert-ASN1-0.27_2         Perl5 module to encode and decode ASN.1 data structures
p5-Convert-BinHex-1.125        Perl module to extract data from Macintosh BinHex files
p5-Crypt-CBC-2.33_1            Perl5 interface to Cipher Block Chaining with DES and IDEA
p5-Crypt-DES-2.07_1            Perl5 interface to DES block cipher
p5-Crypt-OpenSSL-Bignum-0.07   OpenSSL's multiprecision integer arithmetic
p5-Crypt-OpenSSL-DSA-0.18      Perl5 module to DSA signature verification using OpenSSL
p5-Crypt-OpenSSL-EC-1.01       Perl extension for OpenSSL EC (Elliptic Curves) library
p5-Crypt-OpenSSL-ECDSA-0.08    Perl extension for OpenSSL ECDSA
p5-Crypt-OpenSSL-RSA-0.28_1    Perl5 module to RSA encode and decode strings using OpenSSL
p5-Crypt-OpenSSL-Random-0.11   Perl5 interface to the OpenSSL pseudo-random number generator
p5-Crypt-SSLeay-0.72_2         Perl5 interface to allow p5-libwww LWP to make https connections
p5-CryptX-0.044                Crypto toolkit
p5-DBD-SQLite-1.54             Provides access to SQLite3 databases through the DBI
p5-DBD-mysql-4.041             MySQL driver for the Perl5 Database Interface (DBI)
p5-DBI-1.636                   Perl5 Database Interface, required for DBD::* modules
p5-DBIx-Simple-1.35_1          Simplified object oriented interface to Perl DBI
p5-Digest-BubbleBabble-0.02_1  Perl5 interface to a fingerprint in "bubble babble" format
p5-Digest-HMAC-1.03_1          Perl5 interface to HMAC Message-Digest Algorithms
p5-Digest-MD5-2.55             Perl5 interface to the MD5 algorithm
p5-Digest-SHA1-2.13_1          Perl interface to the SHA-1 Algorithm
p5-Encode-Locale-1.05          Determine the locale encoding
p5-File-Listing-6.04_1         Parse directory listings
p5-GSSAPI-0.28_1               Perl extension providing access to the GSSAPIv2 library
p5-Geo-IPfree-1.131650_1       Look up country from an IP Address
p5-HTML-Parser-3.72            Perl5 module for parsing HTML documents
p5-HTML-Tagset-3.20_1          Some useful data table in parsing HTML
p5-HTTP-Cookies-6.01_1         HTTP Cookie jars
p5-HTTP-Daemon-6.01_1          Simple HTTP server class
p5-HTTP-Date-6.02_1            Conversion routines for the HTTP protocol date formats
p5-HTTP-Message-6.11           Representation of HTTP style messages
p5-HTTP-Negotiate-6.01_1       Implementation of the HTTP content negotiation algorithm
p5-IO-HTML-1.001_1             Open an HTML file with automatic charset detection
p5-IO-SessionData-1.03_1       Supporting module for SOAP::Lite
p5-IO-Socket-IP-0.38           Drop-in replacement for IO::Socket::INET supporting IPv4 and IPv6
p5-IO-Socket-SSL-2.038         Perl5 interface to SSL sockets
p5-JSON-2.90_1                 Perl extension to convert to JSON (JavaScript Object Notation)
p5-LWP-MediaTypes-6.02_1       Guess media type for a file or a URL
p5-LWP-Protocol-https-6.06_1   Provide https support for LWP::UserAgent
p5-Locale-gettext-1.06         Message handling functions
p5-MIME-Base32-1.301           Perl5 module for Base32 encodings
p5-MIME-Base64-3.15            Perl5 module for Base64 and Quoted-Printable encodings
p5-MIME-Tools-5.508,2          Set of perl5 modules for MIME
p5-Mail-Tools-2.14             Perl5 modules for dealing with Internet e-mail messages
p5-Module-Implementation-0.09_1 Loads one of several alternate underlying implementations for a module
p5-Module-Runtime-0.014_1      Runtime module handling
p5-Mozilla-CA-20160104         Perl extension for Mozilla CA cert bundle in PEM format
p5-Net-DNS-1.07,1              Perl5 interface to the DNS resolver, and dynamic updates
p5-Net-DNS-SEC-1.03            DNSSEC extensions to Net::DNS
p5-Net-DNS-Zone-Parser-0.02_1  Perl5 preprocessor for normalising a zone file
p5-Net-HTTP-6.09               Low-level HTTP client
p5-Net-IP-1.26_1               Perl extension for manipulating IPv4/IPv6 addresses
p5-Net-LibIDN-0.12_4           This module provides access to the libidn library
p5-Net-SNMP-6.0.1_1            Object oriented interface to SNMP
p5-Net-SSLeay-1.78             Perl5 interface to SSL
p5-Net-XWhois-0.90_5           Whois Client Interface for Perl5
p5-Params-Validate-1.26        Validate method/function parameters
p5-RPC-XML-0.80                XML-RPC client and server library for Perl
p5-SOAP-Lite-1.20              Client and server side SOAP implementation
p5-Socket-2.024                Networking constants and support functions
p5-Task-Weaken-1.04_1          Ensure that a platform has weaken support
p5-Term-ReadKey-2.37           Perl5 module for simple terminal control
p5-Time-HiRes-1.9726_1,1       Perl5 module implementing High resolution time, sleep, and alarm
p5-TimeDate-2.30_2,1           Perl5 module containing a better/faster date parser for absolute dates
p5-Try-Tiny-0.24               Minimal try/catch with proper localization of $@
p5-URI-1.71                    Perl5 interface to Uniform Resource Identifier (URI) references
p5-WWW-RobotRules-6.02_1       Database of robots.txt-derived permissions
p5-XML-Filter-BufferText-1.01_1 Filter to put all characters() in one event
p5-XML-NamespaceSupport-1.11_1 Simple generic namespace support class
p5-XML-Parser-2.44             Perl extension interface to James Clark's XML parser, expat
p5-XML-Parser-Lite-0.721       Lightweight regexp-based XML parser
p5-XML-SAX-0.99_2              Simple API for XML
p5-XML-SAX-Base-1.08_1         Base class SAX Drivers and Filters
p5-XML-SAX-Expat-0.51_1        Simple API for XML
p5-XML-SAX-Writer-0.56         SAX2 XML Writer
p5-libwww-6.15                 Perl5 library for WWW access
p5-perl-ldap-0.6500            Client interface to LDAP (includes Net::LDAP)

It seems that p5-CGI.pm is rather old.

Is that the problem?

**Comment by msimerson** [comment]
Install a newer CGI.pm. I've already added a min ver to Makefile.Pl.
