### ISSUE TITLE
Create new sub-group fails in 2.34

### ISSUE THREAD

**Issue by c1784497** [msimerson/NicTool#183]
### NicTool version
2.34
### perl version
5.18.2-2ubuntu1.1
### OS version
Ubuntu 14.04.5
### Expected behavior
Group created
### Observed behavior
"Internal Server Error"
### Steps to reproduce
Click "New Sub-Group", fill the fields and click "Create".
An "Internal Server Error" error appears and no API call to the NicTool server is made.
If i replace NicTool client 2,34 with 2.33 (server is still 2.34) all is ok so i think a bug in the 2.34 client code.

**Comment by msimerson** [comment]
I just updated my NicTool to the latest (to address issue 185) from `master` and cannot replicate this error.

**Comment by msimerson** [comment]
Have a look in #226. I suspect this is an Apache error encountered on Linux when the apache module mpm_event is used. Switching it to mpm_prefork usually resolves this.
