### ISSUE TITLE
Can't locate Crypt/KeyDerivation.pm in @INC

### ISSUE THREAD

**Issue by m3morx** [msimerson/NicTool#187]
Hi

I get the following error after running the create_tables.pl script on the latest release with Centos 7 and Perl v5.16.3
Can't locate Crypt/KeyDerivation.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at create_tables.pl line 20.
BEGIN failed--compilation aborted at create_tables.pl line 20.

Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-514.10.2.el7.x86_64

Is there a incompatibility with the script to the newsest Perl Version `?

**Comment by ShaunR** [comment]
Try running the following first.

```cpan -i Crypt::KeyDerivation```

**Comment by m3morx** [comment]
doesn't change anything.
Some of the Servers are not reachable i.e.   http://lib.ugent.be/CPAN/modules/02packages.details.txt.gz

**Comment by ShaunR** [comment]
if cpan is unable to download that module and install it then you have other issues going on that are unrelated to nictool.  Paste the full output on a pastebin or something and I can try and assist you further.

**Comment by m3morx** [comment]
in the end, got it to work.
but now im struggling to bring httpd virtualhosts up...

**Comment by msimerson** [comment]
Failure to install CPAN dependencies is a local issue.
