### ISSUE TITLE
[Feature Request] parameterize create_tables.pl

### ISSUE THREAD

**Issue by jensenja** [msimerson/NicTool#188]
Hi,

I'm working on a Dockerfile to containerize both the nictool client and server into one container. I'll be happy to share my work with a pull request when I've tested/vetted. Rather than generate and copy a customized version of `create_tables.pl` into the container, I think it makes a bit more sense to sprinkle some variant of `Getopt` into `create_tables.pl` so you can set up the database non-interactively. I can take a stab at it and include it in the pull request with the Dockerfile if desired.

**Comment by msimerson** [comment]
Adding get it definitely makes sense

**Comment by jensenja** [comment]
I have a question regarding setup - in the [Ubuntu 16 setup wiki](https://github.com/msimerson/NicTool/wiki/Install-NicTool-on-Ubuntu-16) you call out the following steps to extract the nictool client/server:

```
mkdir /usr/local/nictool && cd /usr/local/nictool
tar -xzf ~/NicTool.tar.gz
tar -xzf server/NicToolServer-2.??.tar.gz
tar -xzf client/NicToolClient-2.??.tar.gz
mv server foo; mv NicToolServer-2.?? server
mv client bar; mv NicToolClient-2.?? client
rm -rf foo bar
cd client; perl Makefile.PL; make; sudo make install clean
cd ../server; perl Makefile.PL; make; sudo make install clean
```

for portability reasons it makes more sense to use git to clone your repo in order to setup the client/server, rather than distribute the Dockerfile with a pre-packaged `NicTool-2.XX.tar.gz` how would the steps be different when doing a git clone and building it that way?

**Comment by msimerson** [comment]
Take a look at how I do it [over here](https://github.com/msimerson/Mail-Toaster-6/blob/master/provision-nictool.sh)

**Comment by jensenja** [comment]
Almost done. As you can see I've started documenting utilizing NicTool with Docker in the NicTool wiki. My next question is layout. I was planning on just adding a `docker` subdirectory to this repo with the relevant stuff in it, but honestly I'm not sure if this would be desirable to you since it's kind of adding clutter to the repo. If desired I can just create my own repo for the Docker stuff and then link to it in the Wiki?

I have the changes basically finished to `create_tables.pl` however, so I can just do a git pull on that whenever.

Thoughts?

**Comment by msimerson** [comment]
Adding a .docker directory mostly avoids the clutter issue. Putting all the dist related stuff into something like /dist/docker is even better, as it sets a precedent for an apt, *bsd, or yum package.

**Comment by msimerson** [comment]
In looking at the wiki doc, nice work! Thank you. 

I'm not a fan of self-signed carts in the era of Let's Encrypt but that's a different can of worms. I've stopped enabling SSL on all web servers, mostly because I use nginx, lighttd, node.js, and Apache web servers and having to remember the syntax for each is more annoying than front-ending them all with haproxy.

**Comment by jensenja** [comment]
Understood re: layout points. We can go the /dist/docker route.

I'd not heard of Let's Encrypt - this is pretty cool. Regarding your webservers - so then I'm assuming you're just doing SSL offloading with haproxy?

**Comment by msimerson** [comment]
> so then I'm assuming you're just doing SSL offloading with haproxy?

Yep. Haproxy has a sweet config option for creating a directory for TLS certificates. Just drop them all into a directory (pem encoded, key-cert-chain concatenated) and then point haproxy at that dir with the `ssl crt` option like so:

`bind N.N.N.N:443 ssl crt /etc/ssl.d`

Haproxy inspects each cert, knowns the hostname(s) to serve it for, and automatically does The Right Thing. The only thing left to deal with is making sure certificates are automatically installed and renewed. For that, I use [acme.sh](https://github.com/Neilpang/acme.sh). I wrote a little deployment script (you can see it [here](https://github.com/msimerson/Mail-Toaster-6/blob/master/provision-letsencrypt.sh) that copies new certs into the directory and restarts haproxy. Set it and forget it.
