### ISSUE TITLE
Duplicate A record is possible

### ISSUE THREAD

**Issue by c1784497** [msimerson/NicTool#189]
### NicTool version
Commit 6c4278b92a01e5fe06bfc996dedabb725ae4de24
### perl version
5.18.2-2ubuntu1.1
### OS version
Ubuntu 14.04.5
### Expected behavior
Duplicate record error
### Observed behavior / Steps to reproduce
![testa](https://cloud.githubusercontent.com/assets/6068155/24917135/79f1b348-1edc-11e7-9908-228f728fbc3b.png)

I created issue #185 for this. In the current master branch this issue still exists.
I do the same test as described [here](https://github.com/msimerson/NicTool/issues/185#issue-220991213). Can anyone reproduce this?

**Comment by msimerson** [comment]
I haven't tried yet. What I should do first is to make sure that a test exists that verifies that duplicate records cannot be created. I tested manually when I created #186 but there might be some other issue at play.

**Comment by r4nd0m123** [comment]
I too have encountered this issue. I manually created 127.0.0.1 'test' A record and then created the 45.x.x.x A record.

### NicTool version
Commit 3db1bc7
### perl version
v5.16.3
### OS version
CentOS Linux release 7.3.1611 (Core)

![untitled](https://user-images.githubusercontent.com/22472188/29015156-6ffa9684-7b7f-11e7-93c2-e89f3255985b.png)

**Comment by msimerson** [comment]
@r4nd0m123 , that's not a duplicate record. They share the same name property but have differing addresses. That's a relatively common use pattern for, among other things, round-robin DNS.

**Comment by msimerson** [comment]
I haven't had time to dig into it but I've got a hunch that @c1784497 's issue has to do with mysql version(s) and database encodings.

**Comment by c1784497** [comment]
I use MySQL version 5.5. The database scheme is: https://pastebin.com/zmZ6WiMi

**Comment by msimerson** [comment]
I've just tested and cannot duplicate this. I *think* the issue is that @c1784497 checked out the latest version of NicTool but didn't to the 'make install' step before restarting Apache. Please try and see if that resolves this for you. If not, I'll reopen this issue.
