### ISSUE TITLE
Warning "isn't numeric in numeric gt (>) at" when using nt-export.pl -incremental

### ISSUE THREAD

**Issue by meersau** [msimerson/NicTool#203]
### NicTool version
v2.34

### perl version
This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-gnu-thread-multi

### OS version
Linux  4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

### Expected behavior
$ ./nt_export.pl -nsid 101 -incremental
nsid 101 has 1405 zones, 1 changed, export required, retrieved 1 incremental zones, retrieved 0 deleted, incremental zones, exported, complete

### Observed behavior
$ ./nt_export.pl -nsid 101 -incremental
nsid 101 has 1405 zones, 1 changed, export required*Argument "2017-11-09 14:47:29" isn't numeric in numeric gt (>) at [...]/server/lib/NicToolServer/Export.pm line 480.*
, retrieved 1 incremental zones*Argument "2017-11-09 14:47:29" isn't numeric in numeric gt (>) at [...]/server/lib/NicToolServer/Export.pm line 480.*
, retrieved 0 deleted, incremental zones, exported, complete

### Steps to reproduce
$ ./nt_export.pl -nsid 101 -incremental

### My Workaround
```
diff --git a/server/lib/NicToolServer/Export.pm b/server/lib/NicToolServer/Export.pm
index f1b358b..625a018 100644
--- a/server/lib/NicToolServer/Export.pm
+++ b/server/lib/NicToolServer/Export.pm
@@ -476,6 +476,7 @@ sub get_ns_zones {
         push @args, $p{last_modified};
     }
     else {
+       no warnings qw(numeric);
         if ( $self->incremental && $self->export_required > 1 ) {
             push @descrs, 'incremental';
             $sql .= " AND z.last_modified > ?";
```

Did not found a way to convert the timestamp to an numeric value w/o warning.

Regards,
Alex

**Comment by msimerson** [comment]
Hi Alex, I have a proposed change in #247 that I'd like you to try.
