### ISSUE TITLE
Soap API WSDL

### ISSUE THREAD

**Issue by janvernieuwe** [msimerson/NicTool#210]
Is there anyone who has a WSDL for the SOAP service?
Would be very nice, so that i can generate a soap client from it.

**Comment by rainerduffner** [comment]
AFAIK, there isn't. Matt looked into it, but it's not so easy, apparently.

**Comment by msimerson** [comment]
This was contributed a while ago. I don't grok WSDL but this might help.

[WSDL.xsl.zip](https://github.com/msimerson/NicTool/files/1975618/WSDL.xsl.zip)

**Comment by janvernieuwe** [comment]
Thanks for the reply, unfortunately the file is not a valid wsdl (far from it).
I'm afraid that i'll have to partially reverse engineer it to create a good soap client.

If anyone reads this that has a wsdl for the nictool, please contact me :)

**Comment by janvernieuwe** [comment]
(opting for xml-rpc instead)

**Comment by janvernieuwe** [comment]
For future PHP'ers that might want to interface with the nictool, I had to manhandle the soap request to get it working (without wsdl):

```
class ManhandlingSoapClient extends \SoapClient
{
    public function __doRequest($request, $location, $action, $version, $one_way = null)
    {
        $parts = explode('#', $action);
        $lastPart = array_pop($parts);
        $action = 'http://NICToolServer-api/NicToolServer/SOAP#'.$lastPart;
        $request = preg_replace('/ns1="[^"]*"/', 'ns1="http://NICToolServer-api/NicToolServer/SOAP"', $request);

        return parent::__doRequest($request, $location, $action, $version);
    }
}
```
