### ISSUE TITLE
websites nictool.com and tnpi.net do not work

### ISSUE THREAD

**Issue by darkrecher** [msimerson/NicTool#211]
I know it is not the right place to tell about this issue. But I can not find a better one. All the forums, mails, support, etc. were on these websites.

The websites :

 - http://www.nictool.com/ 
 - https://www.nictool.com/ 
 - http://www.tnpi.net/
 - https://www.tnpi.net/

do not work.

I checked my internet connexion, of course. (And I couldn't go to github if my connexion was down).

**Comment by msimerson** [comment]
Fixed.

**Comment by darkrecher** [comment]
OK. Thank you very much.
