### ISSUE TITLE
Does this work with zones integrated with dhcpd's ddns-updates feature?

### ISSUE THREAD

**Issue by jovrum** [msimerson/NicTool#212]
dhcpd supports RFC 2136 style dynamic DNS updates for automatically managing A, PTR and DHCID records for the hostnames of DHCP clients. Yet such dynamic DNS zones can also have manually managed records where NicTool would be useful. Is it possible to configure NicTool to work smoothly with such a zone, or does NicTool have to always be the sole actor to change zones? The zone I have is extremely dynamic; several updates happen every second.

**Comment by msimerson** [comment]
It's possible, but you'd need to sort out the integration yourself. I think the easiest solution is to put all the dynamic hosts into their own subdomain that's delegated to the dhcpd server and keep the nictool managed zones separate. If you wanted more, you'd need some type of integration using the NicTool API to update zones records when dhcpd processes/emits change events.
