### ISSUE TITLE
XML-RPC

### ISSUE THREAD

**Issue by janvernieuwe** [msimerson/NicTool#215]
### NicTool version
?
### perl version
2.0
### OS version
CentOS
### Expected behavior
get record
### Observed behavior
error
### Steps to reproduce

Hi, i'm trying to use xml-rpc to get a zone record.
This is the xml im sending (the session is redacted, but obtained from a successful login)
*REQUEST*
```
<?xml version="1.0" encoding="iso-8859-1"?>
<methodCall>
    <methodName>get_zone_record</methodName>
    <params>
        <param>
            <value>
                <struct>
                    <member>
                        <name>nt_zone_record_id</name>
                        <value>
                            <string>52280</string>
                        </value>
                    </member>
                    <member>
                        <name>nt_user_session</name>
                        <value>
                            <string>REDACTED</string>
                        </value>
                    </member>
                </struct>
            </value>
        </param>
    </params>
</methodCall>
```
*RESPONSE*
```
<?xml version="1.0" encoding="us-ascii"?>
<methodResponse>
    <params>
        <param>
            <value>
                <struct>
                    <member>
                        <name>error_msg</name>
                        <value>
                            <string>GET_ZONE_RECORD</string>
                        </value>
                    </member>
                    <member>
                        <name>error_code</name>
                        <value>
                            <int>500</int>
                        </value>
                    </member>
                    <member>
                        <name>error_desc</name>
                        <value>
                            <string>Request for unknown action</string>
                        </value>
                    </member>
                </struct>
            </value>
        </param>
    </params>
</methodResponse>
```
I don't know perl, but is this perhaps because of the different casing beween the uppercased string and the keys in the object?

Or am I doing something else wrong?

Regards & thanks in advance!

**Comment by msimerson** [comment]
That is correct. If you look in the [NicTool API docs](https://www.nictool.com/docs/api/) you'll see that all the API commands are lower case.

**Comment by janvernieuwe** [comment]
I am sending it lowercased tho

Sent from mobile

On Jul 17, 2018 4:53 AM, Matt Simerson <notifications@github.com> wrote:

That is correct. If you look in the NicTool API docs<https://www.nictool.com/docs/api/> you'll see that all the API commands are lower case.

**Comment by msimerson** [comment]
Doh, my mistake. I’ll need to look at this further on a large screen. The request _looks_ okay to me. It’s been a while since I’ve used XML.

**Comment by msimerson** [comment]
Also, with NicTool running under Apache and mod_perl, you can find the Perl errors in the Apache logs.

**Comment by janvernieuwe** [comment]
I'm going to see if there is anything useful in those logs.
But this error is one that the nictool itself throws.

Thanks for taking the time!

**Comment by msimerson** [comment]
True enough, but NicTool Server is a mod_perl application, so code is running under mod_perl and therefore the debugging gets output to the Apache logs.

**Comment by janvernieuwe** [comment]
Just looked at the error logs (I'm not managing the server myself) and this is what we get when performing the call:

```
[Wed Jul 18 14:13:55.597846 2018] [core:error] [pid 12308] [client 10.2.0.73:60464] AH00524: Handler for perl-script returned invalid result code 1
[Wed Jul 18 14:13:55.753609 2018] [perl:error] [pid 12306] [client 10.2.0.73:60466] Can't locate object method "new" via package "NicToolServer::" (perhaps you forgot to load "NicToolServer::"?) at /usr/local/share/perl5/NicToolServer.pm line 77.\n
```

**Comment by msimerson** [comment]
From the error message, it appears NicTool isn't installed correctly.
