### ISSUE TITLE
a problem of nictool ptr record

### ISSUE THREAD

**Issue by GitLuckyJ** [msimerson/NicTool#217]
i have a zone of "172.in-addr.arpa."
im input address is “xx.test.com”，but nictool tell me the address is “xx.test.com.172.in-addr.arpa.”
why??
i think that change a error ptr record, because  when i use dig for ptr，the result is “xx.test.com.172.in-addr.arpa.”  not “xx.test.com”

I look forward to your reply

**Comment by msimerson** [comment]
Because you didn’t fully qualify the record (no trailing dot). If you don’t fully qualify a record, the zone name is automatically appended.
