### ISSUE TITLE
how to set a zone that has Extranet record and Intranet record

### ISSUE THREAD

**Issue by Crazy-Geng** [msimerson/NicTool#218]
Hey, Dear Author
I want set a zone ,which has forword Extranet  record and Intranet A record. but i dont konw set it by NicTool.
this  problem puzzle me
I look forward to your reply.

**Comment by Crazy-Geng** [comment]
if i add zone of @, then error"Sanity Error: New Zone,invalid character in zone -- @",so how to handle this problem?
thx

**Comment by msimerson** [comment]
You can't have a zone name with an `@` character. `@` is a special shortcut character used within zone names that means "the name of this zone." 

Having different records for intranet vs extranet is called "split horizon" DNS and is only supported with the tinydns server. Additional work needs to be done to extend export support to BIND and other DNS servers that support it.
