### ISSUE TITLE
How to check if export was successful?

### ISSUE THREAD

**Issue by rainerduffner** [msimerson/NicTool#220]
### NicTool version
2.31
### perl version
5.24
### OS version
FreeBSD 11.1-RELEASE-p8

Has anyone written a plugin for nagios/icinga that checks for the last export and whether it was succesful?

It's visible in the web-gui, but I have a hard time coming up with a check for it.

**Comment by msimerson** [comment]
If I were trying to do this, I'd have a look at `NicToolServer::Export::get_last_ns_export`. You instantiate an Export object, set the nsid property, and then call get_last_ns_export. It returns the last export. Just check its status and exit with an appropriate exit code.

If you accept a CLI arg with the nsid, then you can just the same script for as many nameservers as you have.
