### ISSUE TITLE
Page sometines does not load. Error in apache log

### ISSUE THREAD

**Issue by chofstede** [msimerson/NicTool#226]
### NicTool version
2.34

### perl version
v5.24.1

### OS version
Debian 9

### Expected behavior
Klicking on a link in NicTool loads the desired page

### Observed behavior
Sometimes (every ~10th click), the browser says "Empty Response" and does not load the page
Also in /var/log/apache2/error.log, it prints out this:
[Fri Feb 01 12:23:14.319936 2019] [core:notice] [pid 3867:tid 140016602784960] AH00094: Command line: '/usr/sbin/apache2'
can't find ANONSUB's 'anon23' entry.
can't find ANONSUB's 'anon14' entry.
can't find ANONSUB's 'anon102' entry.
can't find ANONSUB's 'anon41' entry.
can't find ANONSUB's 'anon15' entry.
can't find ANONSUB's 'anon11' entry.

### Steps to reproduce
Klicking links in NicTool. Happens after a few successful page loads

**Comment by msimerson** [comment]
I think you have an Apache and/or mod_perl issue to sort out. I've never seen an issue like this and have no helpful advice. If it were mine, I'd just reinstall NicTool and migrate my database and config files over.

**Comment by chofstede** [comment]
Hi,

1. I installed a fresh machine using the latest debian-9.7.0-amd64-netinst.iso CD from the official homepage.

2. Then installed packages:

`apt-get install -y mysql-client mysql-server libdbix-simple-perl
apt-get install -y apache2 libapache2-mod-perl2 libapache2-mod-perl2-dev libapache-dbi-perl

apt-get install -y curl gcc make gettext rsync libxml2
apt-get install -y libnet-ip-perl libxml-parser-perl libxml-libxml-perl libdigest-hmac-perl
apt-get install -y libjson-perl librpc-xml-perl libsoap-lite-perl`

3. Installed NicTool to /usr/local/nictool

`cd client; perl Makefile.PL; make; sudo make install clean
cd ../server; perl Makefile.PL; make; sudo make install clean`

4. Installed requires perl packages

`apt-get -y install libmodule-build-perl libmime-base32-perl libbind-confparser-perl
apt-get -y install libssl-dev libcrypt-openssl-rsa-perl libcrypt-openssl-dsa-perl
apt-get -y install libshell-perl libnet-dns-perl libyaml-perl bind9utils
cd /usr/local/nictool/server; perl bin/nt_install_deps.pl
cd /usr/local/nictool/client; perl bin/install_deps.pl`

5. Imported our old MySQL database dump, configured nictoolclient and server .conf and configured apache2 by the example docs from http://www.nictool.com/download/nictool.conf

The problem still occurs on the new system. About 90% of requests to the nictool webinterface work
well, the BIND zonefile export runs well. But every few minutes, when you click a link in Nictool,
I get a white page and the error shows up in the /var/log/apache2/error.log that i mentioned.

**Comment by msimerson** [comment]
Sounds like you used the same version of Debian on both systems, so you likely got the same versions of Apache and mod_perl installed, and consequently the same behavior. If there are newer versions of Apache and/or mod_perl available, try installing them. Maybe try an older version and narrow down which version(s) are causing you issues.

I'm running Apache 2.4.37 without issue.

**Comment by chofstede** [comment]
Hi,

I tried the setup now on a new clean Ubuntu 18.04 LTS server (needed some changed MySQL sql_mode settings but everything else was the same)

On Ubuntu it is now running on Apache/2.4.29 (Ubuntu) with mod_perl/2.0.10 and Perl/v5.26.1.

There was an interesting discovery:

At first (after installation), the Problem was not there. Everything was working fine and I didn't get the error, when playing around with the application.

After I dropp'ed the empty db nictool and imported the backup from our old production instance (NicTool 2.11 on Redhat 5) and running "upgrade.pl", the problem immediately re-appeared.

```
If any of the information is incorrect, press Control-C now!
-------------------------
DB_DSN:  DBI:mysql:database=nictool;host=127.0.0.1;port=3306
DB_USER: nictool
DB_PASS: *****removed*****
-------------------------

You made a backup already, right?
  # mysqldump -u root -p nictool > nictool-2011-11-16.sql
  # gzip nictool-2011-11-16.sql

Hit return to continue...

Skipping v2.00 SQL updates (already applied).
Skipping v2.05 SQL updates (already applied).
Skipping v2.08 SQL updates (already applied).
Skipping v2.09 SQL updates (already applied).
Skipping v2.10 SQL updates (already applied).
Skipping v2.11 SQL updates (already applied).
applying v 2.14 SQL updates
ALTER TABLE nt_nameserver MODIFY export_format VARCHAR(12) NOT NULL;

ALTER TABLE nt_nameserver_log MODIFY export_format VARCHAR(12) NULL DEFAULT NULL;
 DROP TABLE IF EXISTS nt_nameserver_export_types;

CREATE TABLE nt_nameserver_export_types ( id tinyint(3) unsigned NOT NULL AUTO_INCREMENT, type varchar(12) NOT NULL DEFAULT '', PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;
 INSERT INTO `nt_nameserver_export_types` (`id`, `type`)
VALUES (1,'tinydns'), (2,'bind'), (3,'maradns'), (4,'powerdns');
 UPDATE nt_options SET option_value='2.14' WHERE option_name='db_version';

applying v 2.15 SQL updates
/* submitted by Arthur Gouros, remove legacy : chars */
UPDATE nt_zone_record SET address = REPLACE(address,'\072',':');

UPDATE nt_options SET option_value='2.15' WHERE option_name='db_version';

applying v 2.16 SQL updates
ALTER TABLE nt_perm ADD column usable_ns VARCHAR(50) AFTER self_write;

UPDATE nt_perm SET usable_ns=(CONCAT_WS(',', usable_ns0,usable_ns1,usable_ns2,usable_ns3,usable_ns4,usable_ns5,usable_ns6,usable_ns7,usable_ns8,usable_ns9));

ALTER TABLE nt_perm DROP column usable_ns0;

ALTER TABLE nt_perm DROP column usable_ns1;

ALTER TABLE nt_perm DROP column usable_ns2;

ALTER TABLE nt_perm DROP column usable_ns3;

ALTER TABLE nt_perm DROP column usable_ns4;

ALTER TABLE nt_perm DROP column usable_ns5;

ALTER TABLE nt_perm DROP column usable_ns6;

ALTER TABLE nt_perm DROP column usable_ns7;

ALTER TABLE nt_perm DROP column usable_ns8;

ALTER TABLE nt_perm DROP column usable_ns9;

ALTER TABLE nt_zone_record MODIFY address VARCHAR(512) NOT NULL;

ALTER TABLE nt_zone_record_log MODIFY address VARCHAR(512) NOT NULL;

UPDATE nt_options SET option_value='2.16' WHERE option_name='db_version';

applying v 2.17 SQL updates
ALTER TABLE nt_user ADD COLUMN is_admin TINYINT(1) UNSIGNED default '0' AFTER email;

UPDATE nt_options SET option_value='2.17' WHERE option_name='db_version';

applying v 2.18 SQL updates
ALTER TABLE resource_record_type ADD column obsolete TINYINT(1) NOT NULL DEFAULT '0' AFTER forward;

REPLACE INTO `resource_record_type` (`id`, `name`, `description`, `reverse`, `forward`, `obsolete`)
VALUES (35,'NAPTR','Naming Authority Pointer',1,1,0), (39,'DNAME','Delegation Name',0,0,0), (43,'DS','Delegation Signer',0,1,0), (44,'SSHFP','Secure Shell Key Fingerprints',0,1,0), (46,'RRSIG','Resource Record Signature',0,1,0), (47,'NSEC','Next Secure',0,1,0), (48,'DNSKEY','DNS Public Key',0,1,0), (50,'NSEC3','Next Secure v3',0,0,0), (51,'NSEC3PARAM','NSEC3 Parameters',0,0,0) ;
 UPDATE nt_zone SET mailaddr=CONCAT('hostmaster.',zone,'.') WHERE mailaddr IS NULL;

UPDATE nt_zone SET mailaddr=CONCAT('hostmaster.',zone,'.') WHERE mailaddr LIKE 'hostmaster.ZONE.TLD%';

UPDATE nt_zone SET mailaddr=SUBSTRING(mailaddr, 1, LENGTH(mailaddr)-1) WHERE mailaddr LIKE '%.';

UPDATE nt_options SET option_value='2.18' WHERE option_name='db_version';

applying v 2.24 SQL updates
ALTER TABLE `nt_nameserver` ADD column address6 VARCHAR(127) NULL DEFAULT NULL AFTER address;

ALTER TABLE `nt_nameserver` ADD column remote_login VARCHAR(127) DEFAULT NULL AFTER address6;

ALTER TABLE `nt_nameserver` ADD column export_type_id INT UNSIGNED DEFAULT '1' AFTER remote_login;

ALTER TABLE `nt_nameserver_log` ADD column `address6` VARCHAR(127) NULL DEFAULT NULL AFTER address;

ALTER TABLE `nt_nameserver_log` ADD column export_type_id INT UNSIGNED NULL AFTER address6;
 DROP TABLE IF EXISTS nt_nameserver_export_types;

DROP TABLE IF EXISTS nt_nameserver_export_type;

CREATE TABLE `nt_nameserver_export_type` ( `id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(16) NOT NULL DEFAULT '', `descr` varchar(56) NOT NULL DEFAULT '', `url` varchar(128) DEFAULT NULL, PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;
 INSERT INTO `nt_nameserver_export_type` (`id`, `name`, `descr`, `url`)
VALUES (1,'djbdns', 'djbdns (tinydns & axfrdns)', 'cr.yp.to/djbdns.html'), (2,'bind', 'BIND (zone files)', 'www.isc.org/downloads/bind/'), (3,'maradns', 'MaraDNS', 'maradns.samiam.org'), (4,'powerdns', 'PowerDNS', 'www.powerdns.com'), (5,'bind-nsupdate','BIND (nsupdate protocol)','www.isc.org/downloads/bind/'), (6,'NSD', 'NSD (Name Server Daemon)', 'www.nlnetlabs.nl/projects/nsd/'), (7,'dynect', 'DynECT Standard DNS','dyn.com/managed-dns/'), (8,'knot', 'Knot DNS', 'www.knot-dns.cz');
 UPDATE nt_nameserver SET export_type_id=1 WHERE export_format IN ('tinydns','djb','djbdns');

UPDATE nt_nameserver SET export_type_id=2 WHERE export_format='bind';

UPDATE nt_nameserver SET export_type_id=3 WHERE export_format='maradns';

UPDATE nt_nameserver SET export_type_id=4 WHERE export_format='powerdns';

ALTER TABLE nt_nameserver DROP column export_format;
 UPDATE nt_options SET option_value='2.24' WHERE option_name='db_version';

applying v 2.27 SQL updates
ALTER TABLE nt_user ADD COLUMN pass_salt VARCHAR(16) AFTER password;

ALTER TABLE nt_user_log ADD COLUMN pass_salt VARCHAR(16) AFTER password;
 INSERT INTO nt_options
VALUES (2,'session_timeout','45'), (3,'default_group','NicTool');
 UPDATE nt_options SET option_value='2.27' WHERE option_name='db_version';

applying v 2.28 SQL updates
ALTER TABLE nt_zone ADD COLUMN last_publish TIMESTAMP DEFAULT 0 AFTER last_modified;
 UPDATE nt_options SET option_value='2.28' WHERE option_name='db_version';

applying v 2.29 SQL updates
ALTER TABLE nt_zone_record_log ADD COLUMN location VARCHAR(2) DEFAULT NULL AFTER other;
 UPDATE nt_options SET option_value='2.29' WHERE option_name='db_version';

applying v 2.30 SQL updates
ALTER table nt_user MODIFY password VARCHAR(255);

ALTER table nt_user_log MODIFY password VARCHAR(255);
 UPDATE nt_options SET option_value='2.30' WHERE option_name='db_version';

applying v 2.32 SQL updates
DROP TABLE IF EXISTS nt_nameserver_qlog;

DROP TABLE IF EXISTS nt_nameserver_qlogfile;
 UPDATE nt_options SET option_value='2.32' WHERE option_name='db_version';

applying v 2.34 SQL updates
INSERT INTO `resource_record_type` (`id`, `name`, `description`, `reverse`, `forward`, `obsolete`)
VALUES (13,'HINFO','Host Info',0,0,1), (256,'URI','URI',0,1,0), (257,'CAA','Certification Authority Authorization',0,1,0);
 UPDATE nt_options SET option_value='2.34' WHERE option_name='db_version';
```

**Comment by msimerson** [comment]
Hrmmmm, that suggests a DB issue. NicTool is overdue for a release and there's a bunch of updates in HEAD since 2.34 was released, including some DB updates (particularly #170). It's worth looking through all the [closed PRs](https://github.com/msimerson/NicTool/pulls?q=is%3Apr+is%3Aclosed) since the 2.34 release. I've been running out of master branch almost since the 2.34 release.

**Comment by msimerson** [comment]
I have a solution that works for me:

```
a2dismod mpm_event
a2enmod mpm_prefork
systemctl restart apache2
```

**Comment by chofstede** [comment]
> I have a solution that works for me:
> 
> ```
> a2dismod mpm_event
> a2enmod mpm_prefork
> systemctl restart apache2
> ```

Thank you very much ! The problem finally is gone

**Comment by tacerus** [comment]
Hello! I don't see how switching to a legacy operational mode of the Apache http daemon is a valid solution - does someone happen to know which Perl library or Apache module is the message `can't find ANONSUB's 'anon1' entry.` originating from?
