### ISSUE TITLE
Add support for A-records in in-addr.arpa

### ISSUE THREAD

**Issue by vv3** [msimerson/NicTool#229]
### NicTool version
2.34

### Expected behavior
When registering new records in a in-addr.arpa zone the 'Type' menu should include A.

Registering A records in in-addr.arpa can be used to "document" subnetting information. See RFC1101

Will a PR for this be accepted?

**Comment by msimerson** [comment]
Yes.

**Comment by vv3** [comment]
I wonder, can this simply be solved with SQL, something like:

`update resource_record_type set reverse=1 where name='a'` ?

Can anyone see any reasons for not doing this?
