### ISSUE TITLE
nt_import requires zone record before resource records

### ISSUE THREAD

**Issue by adamgoryachev** [msimerson/NicTool#231]
### NicTool version
2.34
### perl version
5.24.1
### OS version
Debian Stretch
### Expected behavior
Create the zone and then the resource records
### Observed behavior
Fails to import the file
A       : mail.domain.com:123.123.123.123
could not find zone for mail.domain.com
FATAL   : could not find zone for mail.domain.com

### Steps to reproduce
source data file like this:
+mail.domain.com:123.123.123.123
.domain.com::ns0.otherdomain.com

One solution is to sort the source file before passing to nt_import like so:
egrep '^(\.|Z)' data > tmp_import
egrep -v '^(\.|Z)' data >> tmp_import
Then use nt_import against tmp_import

The better fix would be to have nt_import process the file skipping all records that are not . or Z records. When finished, rewind to the beginning, and process again skipping all . or Z records. This should be reasonably safe, unless we are processing a file from STDIN. 

I don't have any code fix, but perhaps the requirement could be noted in the documentation and/or the manual sort could be included there as an interim solution.

**Comment by msimerson** [comment]
I think a reasonable solution would be as you describe:

- make a first pass of the file that:
    - finds all the zone declarations. 
    - create the zones
- rewind the file handle
    - pass through the file again, ignoring zone declarations.

**Comment by msimerson** [comment]
NicTool 3.0 ([dns-nameserver](https://github.com/NicTool/dns-nameserver)) handles this as described above: it passes through the file extracting the SOA declarations for each zone, then passes through the file again to extract all the records for each discovered zone.
