### ISSUE TITLE
Updating the Makefile.PL with MariaDB

### ISSUE THREAD

**Issue by gerhard-tinned** [msimerson/NicTool#261]
### NicTool version
Current git version as of 2021-07.

### Version
Current Dockerfile uses Debian 8.8 with Mysql 5.5
Planned to upgrade to Debian 10 with MariaDB 10.

### Current State
I have submitted a first PR #260 to prepare the scripts to move from mysql to mariadb. 
Currently the Makefile.PL of the server part includes the mysql dependancy. 

    "DBD::mysql" => "2.0416",

For the Docker setup to function, this needs to be updated to MariaDB dependancy. 

    "DBD::MariaDB" => "0",

### Question

I would prefer not to suggest any breaking changes. As of this, I have observed and tested the following. 

**Debian 8.8 + DBI::MariaDB**
Debian 8.8 does not provide the libmariadb-dev package but only the libmysqld-dev. But thanks to there compatibility, the mariadb dbi module can be compiled on debian 8.8. As such updating the perl module "DBI::mysql" to "DBI::MariaDB" would allow the upgrade from Debian 8.8 to Debian 10. 

**Debian 10 + DBI::MariaDB**
Debinan 10 would need to install the libmariadb-dev as the mysql version is not available any more in debian 10. With that, the MariaDB perl module can be buolt as well. 

In both cases, the perl module allows connecting to a Mysql 5.5. 

I do not know if there is any way to seperate the perl module dependancy list in the Makefile.PL but at least for Linux it seems that simply changing the module name to MariaDB would solf it in a compatible way. Not sure about BSD and other OS types. 

Please suggest the best way to introduce this change.

**Comment by msimerson** [comment]
Long term my plan is to ditch SQL entirely and move the DNS data into a document store. Beyond that, I haven't given it much thought.

**Comment by gerhard-tinned** [comment]
So, Can I send you a PR with the MariaDB dependancy in the Makefile.PL ?? So far under Debian 8.8 it works.

**Comment by gerhard-tinned** [comment]
Hi, I have created PR #262. Is there a chance that will be merged? I know that change has the potential of introducing a breaking change. If there is a way to introduce the changes without causing a breaking change, please let me know and I will update it.

**Comment by msimerson** [comment]
I haven't had a chance to look in more detail. Im thinking there's a couple paths forward:

1. Switch dependency to MariaDB
2. Add a bash/sh pre-script that rewrites all the dep files that allows switching engines

**Comment by gerhard-tinned** [comment]
Well, at this point, all the scripts involved (except very few scripts are already mysql AND MqriaDB compatible. 

* server/sql/dump_schema.pl
* server/sql/upgrade.pl 
* server/bin/nt_powerdns.pl

I never used those but from the code, server/sql/upgrade.pl  is asking for the dsn and should therefore be compatible with Mariadb even with the default pointing to mysql.

The server/sql/dump_schema.pl seems to have hardcoded dsn and database credentials. Not sure how to proceed with this file. 

As in the dump_schema, the server/bin/nt_powerdns.pl has all database credentials and the dsn hardcoded in the script. Editing the dsn while you are changing the credentials and even that script should work. Not sue if that is a the intention, but it would work. 

The only remaining files where I could find a reference to mysql dbi connectors is in the .test directory and the travis.yml. Sadly I have no clue how those are used. If they need changing, please point me the right direction and I will change them too.
