### ISSUE TITLE
Please add howto setup NicTool with nginx to your documentation

### ISSUE THREAD

**Issue by Popyllol** [msimerson/NicTool#298]
### NicTool version
2.34
### perl version
v5.26.1
### OS version
Linux / Ubuntu 18.04.6 LTS
### Expected behavior
NicTool runs with nginx and fastcgi
### Observed behavior
NicTool almost runs with nginx and fastcgi
### Steps to reproduce
With nginx and fastcgi
```
server {
        listen 127.0.0.1:8443 default_server;
...
        root /var/www/nictool/client/htdocs;
        index index.cgi;

        location ~ ^/images($|/.*) {
                alias /var/www/nictool/client/htdocs/images$1;
        }

        location ~ \.(pl|cgi)$ {
                try_files $uri =404;
                gzip off;
                fastcgi_pass  unix:/var/run/fcgiwrap.socket;
                fastcgi_index index.cgi;
                fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                fastcgi_cache_key "$scheme$request_method$host$request_uri";
                include fastcgi_params;
        }
}
```
the NicTool displays a second Content-Type line:
```
$ curl --insecure -D - https://127.0.0.1:8443/index.cgi 2>/dev/null
HTTP/1.1 200 OK
Server: nginx/1.14.0 (Ubuntu)
Content-Type: text/html; charset=ISO-8859-1
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: NicTool=; path=/; expires=Thu, 06-Jan-2022 16:08:56 GMT; secure
Date: Fri, 07 Jan 2022 16:08:56 GMT

Content-Type: text/html; charset=utf-8

<!DOCTYPE html>
<html>
<head>
  <title>NicTool</title>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
  <link rel="stylesheet" href="nt-style.css" type="text/css" media="screen" />
</head>
...
```
Can you please give me any advice how to get this work?
Thank you!
   Lars

**Comment by msimerson** [comment]
I got this working with lighttpd a few years back and it worked well enough. I was hoping to decouple NicTool Server from Apache + mod_perl but ultimately failed, and then gave up on using lighttpd / nginx entirely.

My future NicTool efforts are directed [here](https://github.com/msimerson/NicTool/issues/276), which will resolve this issue in a different way.

**Comment by Popyllol** [comment]
Thank you for your answer!
I am really looking forward to the RESTful API!
