### ISSUE TITLE
running nt_export in a NS conceals the list of nameservers

### ISSUE THREAD

**Issue by msimerson** [msimerson/NicTool#72]
I have something related that I'd like you to consider. Most NicTool installs run the export processes for **all** of their name servers on the NicTool host. Example:
1. nictool.example.com
2. ns1.example.com
3. ns2.example.com
4. ns3.example.com

Quite often, the NicTool server also serves as one of the name servers. So, in this case, nictool is actually a CNAME of ns1. When I do this, things are going to work out poorly:

``` sh
cd /usr/local/nictool/ns2.example.com
perl ./nt_export.pl
```

I won't get a list of NSIDs to choose from, and I won't easily be able to get at them either.

**Comment by msimerson** [comment]
This is related to #70 by @hickey

**Comment by hickey** [comment]
Sorry, I missed this comment when you left it. 

Yes, there are situations where the NSID can not be discovered automatically, hence why the traditional way of generating for a specific NSID is still supported. I will look to create a list of NSIDs if the NSID can not be detected and has not been specified.

**Comment by msimerson** [comment]
Actually, the problem isn't that the NSID can't be discovered automatically, but that it will be automatically discovered incorrectly, and there won't be any way to get at the list. What I propose is that rather than automatically discovering the NSID, present the list with the "detected" one set as the default.
