### ISSUE TITLE
nt_import.pl broken

### ISSUE THREAD

**Issue by pertoft** [msimerson/NicTool#73]
I have just installed Nictool V. 2.31 and import is not longer working. I can confirm the same issues with the git version.

````
root@amnesio:~/home/namedb# perl /usr/local/nictool/server/bin/nt_import.pl --user=root --pass=XXXX  --type=bind --file /home/pto/home/namedb/gen/named.pto-test.conf --verbose
loading type: bind
$VAR1 = {
          'deleted' => '0',
          'email' => 'pto@telenor.dk',
          'error_code' => '200',
          'error_desc' => '',
          'error_msg' => 'OK',
          'first_name' => 'Root',
          'group_create' => '1',
          'group_delete' => '1',
          'group_write' => '1',
          'groupname' => 'NicTool',
          'inherit_group_permissions' => '1',
          'inherit_perm' => undef,
          'is_admin' => undef,
          'last_name' => 'User',
          'nameserver_create' => '1',
          'nameserver_delete' => '1',
          'nameserver_write' => '1',
          'nt_group_id' => '1',
          'nt_user_id' => '1',
          'nt_user_session' => '54d8c939187d044c',
          'pass_salt' => 'uDN*Ql6DKP](KdSO',
          'self_write' => '1',
          'usable_ns' => '2',
          'user_create' => '1',
          'user_delete' => '1',
          'user_write' => '1',
          'username' => 'root',
          'zone_create' => '1',
          'zone_delegate' => '1',
          'zone_delete' => '1',
          'zone_write' => '1',
          'zonerecord_create' => '1',
          'zonerecord_delegate' => '1',
          'zonerecord_delete' => '1',
          'zonerecord_write' => '1'
        };

Starting import using: /home/pto/home/namedb/gen/named.pto-test.conf
zone: ip.cybercity.dk   from    gen/11/P.ip.cybercity.dk
creating zone ip.cybercity.dk
Can't locate object method "nameservers" via package "NicToolServer::Import::BIND::Conf_Parser" at /usr/local/share/perl/5.14.2/NicToolServer/Import/Base.pm line 92.
root@amnesio:~/home/namedb#
````

**Comment by msimerson** [comment]
Sorry 'bout that. There's a bit more work to be done on the importing. For now, installing NicTool 2.30, doing the import and then upgrading would be the easiest workaround. I'm not sure when I'll get time to test and fix this.

**Comment by msimerson** [comment]
Untested, but this *might* fix it:
```diff
diff --git a/server/lib/NicToolServer/Import/BIND.pm b/server/lib/NicToolServer/Import/BIND.pm
index 4a66a90..af61fc4 100755
--- a/server/lib/NicToolServer/Import/BIND.pm
+++ b/server/lib/NicToolServer/Import/BIND.pm
@@ -39,7 +39,7 @@ sub import_records {
     $self->get_import_file( $file ) or return;
 
     my $p = NicToolServer::Import::BIND::Conf_Parser->new;
-    foreach ( qw/ nt group_id nameservers / ) {
+    foreach ( qw/ nt group_id / ) {
         $p->{$_} = $self->{$_};
     };
     #print "loaded parser\n";
```

**Comment by pertoft** [comment]
I have tried your workaround, but there is still references in Base.pm which fails:
/usr/local/share/perl/5.14.2/NicToolServer/Import/Base.pm line 92.

**Comment by rduffner** [comment]
Hi,

strangely, when I try to use the git-code, I get
Can't locate Shell.pm in @INC (you may need to install the Shell module) (@INC contains: lib . /usr/local/lib/perl5/site_perl/mach/5.18 /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.18/mach /usr/local/lib/perl5/5.18 /usr/local/lib/perl5/site_perl/5.18 /usr/local/lib/perl5/site_perl/5.18/mach) at /usr/local/lib/perl5/site_perl/Net/DNS/Zone/Parser.pm line 30, <STDIN> line 4.
BEGIN failed--compilation aborted at /usr/local/lib/perl5/site_perl/Net/DNS/Zone/Parser.pm line 30, <STDIN> line 4.
Compilation failed in require at /usr/local/lib/perl5/site_perl/NicToolServer/Import/BIND.pm line 17, <STDIN> line 4.
BEGIN failed--compilation aborted at /usr/local/lib/perl5/site_perl/NicToolServer/Import/BIND.pm line 17, <STDIN> line 4.
Compilation failed in require at ./nt_import.pl line 68, <STDIN> line 4.


Shell.pm is installed.
(nictool </root>) 0 # find /usr/local/lib/perl5 -name "Shell.pm"
/usr/local/lib/perl5/5.18/CPANPLUS/Shell.pm
/usr/local/lib/perl5/5.18/CPAN/Shell.pm

When I include it via "use", I get
Can't locate object method "new" via package "SOAP::Transport::HTTP::Client" at /usr/local/lib/perl5/site_perl/SOAP/Transport/HTTP.pm line 113, <STDIN> line 4.

**Comment by bpbp-boop** [comment]
I ran into this today. I tried to download 2.30 to get the imports done but the cart software will always download the latest version, no matter which link is picked.

**Comment by msimerson** [comment]
Hey @bpbp-boop , just grab it from here: https://github.com/msimerson/NicTool/releases

**Comment by bpbp-boop** [comment]
Thanks, that worked! :tada:

**Comment by simonb256** [comment]
I seem to be having a very similar issue. Running version 2.3.3 on Centos7.
Trying to import from our existing BIND servers, it complains Net::DNS::Zone::Parser is not present, although it is installed on the system:

`Starting import using: /root/static.conf
zone: somedomain.com 	from	somedomain.com.zone
Can't locate object method "new" via package "Net::DNS::Zone::Parser" (perhaps you forgot to load "Net::DNS::Zone::Parser"?) at /usr/local/share/perl5/NicToolServer/Import/BIND.pm line 55, <$FH> line 5.
[root@nictool ~]# cpan -i Net::DNS::Zone::Parser
Reading '/root/.cpan/Metadata'
  Database was generated on Fri, 07 Oct 2016 08:29:02 GMT
Net::DNS::Zone::Parser is up to date (0.02).`

Do I need to regress to v2.30 as mentioned earlier in this bug?

**Comment by simonb256** [comment]
I have just found that in /usr/local/share/perl5/NicToolServer/Import/BIND.pm
The following was commented out:
 `use Net::DNS::Zone::Parser;`

i will take snapshot of my VM running NicTool and test now uncommented.
