### ISSUE TITLE
Nictool-2.30: nt_import.pl parse error

### ISSUE THREAD

**Issue by pertoft** [msimerson/NicTool#74]
Nictool version: 2.30
Operation system: Ubuntu 12.04 LTS
Perl: v5.14.2
nt_install_deps.pl: all modules installed

cd  /home/pto/home/namedb
perl /usr/local/nictool/server/bin/nt_import.pl --verbose 1 --nameserver=4 --user=root --pass=XXXXX --type=bind --file /home/pto/home/namedb/gen/named.pto-test.conf

loading type: bind
$VAR1 = {
          'deleted' => '0',
          'email' => 'test@example.com',
          'error_code' => '200',
          'error_desc' => '',
          'error_msg' => 'OK',
          'first_name' => 'Root',
          'group_create' => '1',
          'group_delete' => '1',
          'group_write' => '1',
          'groupname' => 'NicTool',
          'inherit_group_permissions' => '1',
          'inherit_perm' => undef,
          'is_admin' => undef,
          'last_name' => 'User',
          'nameserver_create' => '1',
          'nameserver_delete' => '1',
          'nameserver_write' => '1',
          'nt_group_id' => '1',
          'nt_user_id' => '1',
          'nt_user_session' => '54d9d0d51600b524',
          'pass_salt' => '*******',
          'self_write' => '1',
          'usable_ns' => '2',
          'user_create' => '1',
          'user_delete' => '1',
          'user_write' => '1',
          'username' => 'root',
          'zone_create' => '1',
          'zone_delegate' => '1',
          'zone_delete' => '1',
          'zone_write' => '1',
          'zonerecord_create' => '1',
          'zonerecord_delegate' => '1',
          'zonerecord_delete' => '1',
          'zonerecord_write' => '1'
        };
nameservers: 4

Starting import using: /home/pto/home/namedb/gen/named.pto-test.conf
zone: ip.cybercity.dk   from    gen/11/P.ip.cybercity.dk
creating zone ip.cybercity.dk
Sanity error ( The mailaddr format replaces the @ with a . (dot). ), $VAR1 = {
          'contact' => 'zonec@cybercity.dk.',
          'description' => 'imported',
          'expire' => 604800,
          'minimum' => 300,
          'refresh' => 10800,
          'retry' => 3600,
          'ttl' => 300,
          'zone' => 'ip.cybercity.dk'
        };
A : lo0.7-tech.ip.cybercity.dk  130.227.88.80
The 'zone_id' parameter (undef) to NicToolServer::Import::Base::nt_create_record was an 'undef', which is not one of the allowed types: scalar
 at /usr/local/share/perl/5.14.2/NicToolServer/Import/Base.pm line 124
        NicToolServer::Import::Base::nt_create_record(undef, 'zone_id', undef, 'type', 'A', 'name', 'lo0.7-tech', 'address', 130.227.88.80, ...) called at /usr/local/share/perl/5.14.2/NicToolServer/Import/BIND.pm line 105
        NicToolServer::Import::BIND::zr_a('NicToolServer::Import::BIND::Conf_Parser=HASH(0x1aef4d8)', 'Net::DNS::RR::A=HASH(0x2125480)', 'ip.cybercity.dk') called at /usr/local/share/perl/5.14.2/NicToolServer/Import/BIND.pm line 65
        NicToolServer::Import::BIND::import_zone('NicToolServer::Import::BIND::Conf_Parser=HASH(0x1aef4d8)', 'ip.cybercity.dk', 'gen/11/P.ip.cybercity.dk') called at /usr/local/share/perl/5.14.2/NicToolServer/Import/BIND.pm line 338
        NicToolServer::Import::BIND::Conf_Parser::handle_zone('NicToolServer::Import::BIND::Conf_Parser=HASH(0x1aef4d8)', 'ip.cybercity.dk', 'in', 'master', 'HASH(0x178cad8)') called at /usr/local/share/perl/5.14.2/BIND/Conf_Parser.pm line 762
        BIND::Conf_Parser::parse_zone('NicToolServer::Import::BIND::Conf_Parser=HASH(0x1aef4d8)') called at /usr/local/share/perl/5.14.2/BIND/Conf_Parser.pm line 856
        BIND::Conf_Parser::parse_conf('NicToolServer::Import::BIND::Conf_Parser=HASH(0x1aef4d8)') called at /usr/local/share/perl/5.14.2/BIND/Conf_Parser.pm line 887
        BIND::Conf_Parser::parse_fh('NicToolServer::Import::BIND::Conf_Parser=HASH(0x1aef4d8)', 'GLOB(0x1aef490)') called at /usr/local/share/perl/5.14.2/NicToolServer/Import/BIND.pm line 46
        NicToolServer::Import::BIND::import_records('NicToolServer::Import::BIND=HASH(0xdbcd40)', '/home/pto/home/namedb/gen/named.pto-test.conf') called at /usr/local/nictool/server/bin/nt_import.pl line 64
/usr/local/nictool/server/bin
root@amnesio:/usr/local/nictool/server/bin#

named.pto-test.conf:
zone "ip.cybercity.dk" { type master; file "gen/11/P.ip.cybercity.dk"; };

The zone file (gen/11/P.ip.cybercity.dk):
; THIS FILE IS GENERATED, DO NOT EDIT
$TTL 300
@               IN      SOA     ns1.cybercity.dk.       zonec.cybercity.dk. (
                                2013011003      ; Serial
                                10800           ; Refresh
                                3600            ; Retry
                                604800          ; Expire
                                300)            ; Minimum
@                       NS      ns1.cybercity.dk.
@                       NS      ns2.cybercity.dk.
@                       NS      ns3.cybercity.dk.
@                       NS      ns4.cybercity.dk.

lo0.7-tech      A       212.242.40.51
lo0.sagem       A       212.242.40.3

Note: the zone file is very long and i have left some out. 

I have tried using the version from git but its currently broken according to issue #73

**Comment by pertoft** [comment]
I have made a workaround. It seems like the Bind parser interprets the zone contact as zonec@cybercity.dk in this case. And the "@" in the $p{contact} is illegal and is rejected by the webservice.

I have made a work around which rewrites the "@" to a "." tested and everything seems to work.

root@amnesio:/usr/local/nictool/server# diff ~/nictool/NicTool-2.30/server/NicToolServer-2.30/lib/NicToolServer/Import/Base.pm /usr/local/share/perl/5.14.2/NicToolServer/Import/Base.pm
94a95,97
>     #Replace @ int Zone Contact with a . to obey zone naming standards
>     $p{contact} =~ s/@/./g;
>

**Comment by msimerson** [comment]
Ah, that issue was [already fixed here](https://github.com/msimerson/NicTool/blob/master/server/lib/NicToolServer/Import/Base.pm#L91)
