### ISSUE TITLE
A and PTR records auto-generation

### ISSUE THREAD

**Issue by pertoft** [msimerson/NicTool#75]
Hi,

I dont know if this feature exists, otherwise i would like to request it.

We are a T2 ISP and we are trying to integrate NicTool as our DNS management system replacing our legacy scripts bases DNS management with NicTool. 

Today we have build scripts which auto generates reverse dns zones (192.0.10.1 0x12345678.customer.test.com) and then update all PTR records if they have A-records (A www.test.com 192.0.0.1 will update the PTR for 192.0.0.1 to match www.test.com). 

How would you integrate this part into NicTool?

Im thinking to rewrite the reverse dns zone generator script to write bind zones to a directory, then use nt_import.pl to import the PTR zones. And if changes are made, re-do the steps and overwrite the old data.

Next step could be using the API or database access to lookup all A-records and update the PTR zones with the records.

What do you think? Do you have any plans to support a feature like this?

Thanks,
Per N. Toft
Telenor DK

**Comment by msimerson** [comment]
I've written quite a few scripts that automate the creation of forward and reverse matching DNS. The problem is, every single one has been unique to the organization using it. There just isn't a one-size-fits-all or even one-size-fits-most way to automatically create matching rDNS. There's an open issue #41 for doing it. Here's the salient bits of the last "add a host and matching IPv4 and IPv6 rDNS" script I wrote (but you'll notice, it has some extra not-included bits that determine what the right rDNS zone is):
```perl
$fqdn ||= $util->ask("fully qualified domain name (FQDN)");
$ip   ||= $util->ask("IPv4 address");
$ip6  ||= $util->ask("IPv6 address");       # get optional IPv6 IP

usage() if ( ! $fqdn || ( ! $ip && ! $ip6 ) );

$cnt->nt_connect();                         # connect to nictool

my ($host, $domain) = split /\./, $fqdn, 2; # get the $host / $domain
#print "host: $host\n";
#print "domn: $domain\n";

my $zone_id = $cnt->get_zone_id( $domain )  # find the $domain zone
    or die "could not find zone ID for $domain\n";

foreach my $t ( qw/ A AAAA / ) {

    my $now = $cnt->_get_zone_records( $zone_id, $host, $t ); # find the host record
    if ( $now ) {
        warn "$t record exists\n";
        my %new = %$now;
        $new{address} = $t eq 'A' ? $ip : $ip6;
        $cnt->update_record( \%new, $now );     # update the $host record
    }
    else {
        my $address = $t eq 'A' ? $ip : $ip6;
        if ( $address ) {
            $cnt->create_forward( $fqdn, $address, $t );
        };
    }
};

my $now = $cnt->get_reverse_zone_record($ip);  # find the reverse zone
if ( $now ) {
    my %new = %$now;
    $new{address} = "$fqdn.";
    $cnt->log( "updating PTR for $ip to $fqdn.\n" );
    $cnt->update_record( \%new, $now );           # update the PTR
};

if ( $ip6 && $ip6 ne '' ) {
    $now = $cnt->get_reverse_zone_record_ipv6($ip6);  # find the IPv6 reverse zone
    if ( $now ) {
# add IPv6 PTR
        my %new = %$now;
        $new{address} = "$fqdn.";
        $cnt->log( "updating PTR for $ip6 to $fqdn.\n" );
        $cnt->update_record( \%new, $now );           # update the PTR
    } 
    else {
        $cnt->create_ptr( $ip6, "$fqdn.");
    };
};
```

**Comment by pertoft** [comment]
Thanks for the reply. It was very helpful!

I see you have cut'n'pasted from https://github.com/msimerson/NicTool/tree/master/server/api

The code is very helpful for me and ill try and brew a new clever script which interfaces to Nictool for reverse DNS management.

If i get it working, i will publish it here :)

Thanks
Per
