### ISSUE TITLE
After update to 2.32, I can't login anymore

### ISSUE THREAD

**Issue by rduffner** [msimerson/NicTool#91]
Hi, I upgraded to 2.32 and now I can't login anymore.
If I use the root-user, I get "Invalid password".
If I use a user in a sub-group, I get "Invalid group".
I've bundled-up 2.32 myself in a VM that runs slightly newer packages (2015Q3 vs. 2015Q2) than the actual NicTool installation.

Is there a quick way to re-set the root-password?

**Comment by msimerson** [comment]
I haven't had a chance to test 2.32 (hence, it not being available in the TNPI store). You can set the root password in mysql, just save it as plain text and it'll work. Then change it via the web UI to get it crypted.

**Comment by rduffner** [comment]
OK, so this worked. I reset the passwords and they worked again.

**Comment by msimerson** [comment]
I'm not sure how this was achieved, but in my own upgrade from 2.31 to 2.33, I have had no such issues. If anyone else experiences this, we'll re-open the issue and investigate.
